// Package firepitclient contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package firepitclient

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. The generated client owns (de)serialization via the codec;
// the carrier only moves bytes, so it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// AuthClient is a typed client for the AuthService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type AuthClient struct {
	transport Transport
}

func NewAuthClient(transport Transport) *AuthClient {
	return &AuthClient{transport: transport}
}

// operation begin-login has a payload csilgen can't (de)serialize; handle it manually

func (c *AuthClient) Logout(ctx context.Context, req Empty) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "auth", "Logout", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

// operation whoami has a payload csilgen can't (de)serialize; handle it manually

// BoardClient is a typed client for the BoardService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type BoardClient struct {
	transport Transport
}

func NewBoardClient(transport Transport) *BoardClient {
	return &BoardClient{transport: transport}
}

func (c *BoardClient) ListBoards(ctx context.Context, req ListBoardsRequest) (BoardPage, error) {
	var csilZero BoardPage
	csilResp, csilErr := c.transport.Call(ctx, "board", "ListBoards", EncodeListBoardsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBoardPage(csilResp)
}

// operation get-board has a payload csilgen can't (de)serialize; handle it manually

// operation create-board has a payload csilgen can't (de)serialize; handle it manually

// operation update-board has a payload csilgen can't (de)serialize; handle it manually

// operation archive-board has a payload csilgen can't (de)serialize; handle it manually

// operation set-board-member has a payload csilgen can't (de)serialize; handle it manually

// operation remove-board-member has a payload csilgen can't (de)serialize; handle it manually

// ThreadClient is a typed client for the ThreadService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ThreadClient struct {
	transport Transport
}

func NewThreadClient(transport Transport) *ThreadClient {
	return &ThreadClient{transport: transport}
}

func (c *ThreadClient) ListPosts(ctx context.Context, req ListPostsRequest) (PostPage, error) {
	var csilZero PostPage
	csilResp, csilErr := c.transport.Call(ctx, "thread", "ListPosts", EncodeListPostsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePostPage(csilResp)
}

func (c *ThreadClient) GetThread(ctx context.Context, req GetThreadRequest) (Thread, error) {
	var csilZero Thread
	csilResp, csilErr := c.transport.Call(ctx, "thread", "GetThread", EncodeGetThreadRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeThread(csilResp)
}

// operation create-post has a payload csilgen can't (de)serialize; handle it manually

// operation create-comment has a payload csilgen can't (de)serialize; handle it manually

// operation edit-post has a payload csilgen can't (de)serialize; handle it manually

// operation edit-comment has a payload csilgen can't (de)serialize; handle it manually

func (c *ThreadClient) ListRevisions(ctx context.Context, req TargetRef) (RevisionList, error) {
	var csilZero RevisionList
	csilResp, csilErr := c.transport.Call(ctx, "thread", "ListRevisions", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRevisionList(csilResp)
}

// operation delete-post has a payload csilgen can't (de)serialize; handle it manually

// operation delete-comment has a payload csilgen can't (de)serialize; handle it manually

// EndorsementClient is a typed client for the EndorsementService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type EndorsementClient struct {
	transport Transport
}

func NewEndorsementClient(transport Transport) *EndorsementClient {
	return &EndorsementClient{transport: transport}
}

// operation endorse has a payload csilgen can't (de)serialize; handle it manually

// operation retract has a payload csilgen can't (de)serialize; handle it manually

func (c *EndorsementClient) ListEndorsements(ctx context.Context, req TargetRef) (EndorsementList, error) {
	var csilZero EndorsementList
	csilResp, csilErr := c.transport.Call(ctx, "endorsement", "ListEndorsements", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEndorsementList(csilResp)
}

// SettingsClient is a typed client for the SettingsService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SettingsClient struct {
	transport Transport
}

func NewSettingsClient(transport Transport) *SettingsClient {
	return &SettingsClient{transport: transport}
}

func (c *SettingsClient) GetSettings(ctx context.Context, req Empty) (UserSettings, error) {
	var csilZero UserSettings
	csilResp, csilErr := c.transport.Call(ctx, "settings", "GetSettings", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserSettings(csilResp)
}

// operation update-settings has a payload csilgen can't (de)serialize; handle it manually

func (c *SettingsClient) ListMentionGrants(ctx context.Context, req Empty) (MentionGrantList, error) {
	var csilZero MentionGrantList
	csilResp, csilErr := c.transport.Call(ctx, "settings", "ListMentionGrants", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMentionGrantList(csilResp)
}

// operation grant-mention has a payload csilgen can't (de)serialize; handle it manually

// operation revoke-mention has a payload csilgen can't (de)serialize; handle it manually

// SocialClient is a typed client for the SocialService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SocialClient struct {
	transport Transport
}

func NewSocialClient(transport Transport) *SocialClient {
	return &SocialClient{transport: transport}
}

func (c *SocialClient) ListFriendGroups(ctx context.Context, req Empty) (FriendGroupList, error) {
	var csilZero FriendGroupList
	csilResp, csilErr := c.transport.Call(ctx, "social", "ListFriendGroups", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeFriendGroupList(csilResp)
}

// operation create-friend-group has a payload csilgen can't (de)serialize; handle it manually

// operation delete-friend-group has a payload csilgen can't (de)serialize; handle it manually

// operation add-friend has a payload csilgen can't (de)serialize; handle it manually

// operation remove-friend has a payload csilgen can't (de)serialize; handle it manually

// SubscriptionClient is a typed client for the SubscriptionService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SubscriptionClient struct {
	transport Transport
}

func NewSubscriptionClient(transport Transport) *SubscriptionClient {
	return &SubscriptionClient{transport: transport}
}

// operation subscribe has a payload csilgen can't (de)serialize; handle it manually

// operation unsubscribe has a payload csilgen can't (de)serialize; handle it manually

// operation set-muted has a payload csilgen can't (de)serialize; handle it manually

func (c *SubscriptionClient) ListSubscriptions(ctx context.Context, req Empty) (SubscriptionList, error) {
	var csilZero SubscriptionList
	csilResp, csilErr := c.transport.Call(ctx, "subscription", "ListSubscriptions", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSubscriptionList(csilResp)
}

// ReadClient is a typed client for the ReadService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ReadClient struct {
	transport Transport
}

func NewReadClient(transport Transport) *ReadClient {
	return &ReadClient{transport: transport}
}

func (c *ReadClient) MarkRead(ctx context.Context, req TargetRef) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "read", "MarkRead", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *ReadClient) MarkUnread(ctx context.Context, req TargetRef) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "read", "MarkUnread", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *ReadClient) UnreadSummary(ctx context.Context, req Empty) (UnreadSummary, error) {
	var csilZero UnreadSummary
	csilResp, csilErr := c.transport.Call(ctx, "read", "UnreadSummary", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUnreadSummary(csilResp)
}

// NotificationClient is a typed client for the NotificationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type NotificationClient struct {
	transport Transport
}

func NewNotificationClient(transport Transport) *NotificationClient {
	return &NotificationClient{transport: transport}
}

func (c *NotificationClient) ListNotifications(ctx context.Context, req ListNotificationsRequest) (NotificationPage, error) {
	var csilZero NotificationPage
	csilResp, csilErr := c.transport.Call(ctx, "notification", "ListNotifications", EncodeListNotificationsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeNotificationPage(csilResp)
}

func (c *NotificationClient) MarkNotificationRead(ctx context.Context, req NotificationIDs) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "notification", "MarkNotificationRead", EncodeNotificationMarkNotificationReadRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *NotificationClient) MarkAllRead(ctx context.Context, req Empty) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "notification", "MarkAllRead", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

// IntegrationClient is a typed client for the IntegrationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type IntegrationClient struct {
	transport Transport
}

func NewIntegrationClient(transport Transport) *IntegrationClient {
	return &IntegrationClient{transport: transport}
}

// operation create-github-mapping has a payload csilgen can't (de)serialize; handle it manually

func (c *IntegrationClient) ListGithubMappings(ctx context.Context, req Empty) (MappingList, error) {
	var csilZero MappingList
	csilResp, csilErr := c.transport.Call(ctx, "integration", "ListGithubMappings", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMappingList(csilResp)
}

// operation delete-github-mapping has a payload csilgen can't (de)serialize; handle it manually

// operation add-trusted-domain has a payload csilgen can't (de)serialize; handle it manually

// operation remove-trusted-domain has a payload csilgen can't (de)serialize; handle it manually

func (c *IntegrationClient) ListTrustedDomains(ctx context.Context, req Empty) (DomainList, error) {
	var csilZero DomainList
	csilResp, csilErr := c.transport.Call(ctx, "integration", "ListTrustedDomains", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDomainList(csilResp)
}
