// Package firepitclient contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package firepitclient

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. The generated client owns (de)serialization via the codec;
// the carrier only moves bytes, so it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// AuthClient is a typed client for the AuthService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type AuthClient struct {
	transport Transport
}

func NewAuthClient(transport Transport) *AuthClient {
	return &AuthClient{transport: transport}
}

func (c *AuthClient) BeginLogin(ctx context.Context, req BeginLoginRequest) (BeginLoginResponse, error) {
	var csilZero BeginLoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "auth", "BeginLogin", EncodeBeginLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBeginLoginResponse(csilResp)
}

func (c *AuthClient) Logout(ctx context.Context, req Empty) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "auth", "Logout", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *AuthClient) Whoami(ctx context.Context, req Empty) (UserProfile, error) {
	var csilZero UserProfile
	csilResp, csilErr := c.transport.Call(ctx, "auth", "Whoami", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserProfile(csilResp)
}

// BoardClient is a typed client for the BoardService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type BoardClient struct {
	transport Transport
}

func NewBoardClient(transport Transport) *BoardClient {
	return &BoardClient{transport: transport}
}

func (c *BoardClient) ListBoards(ctx context.Context, req ListBoardsRequest) (BoardPage, error) {
	var csilZero BoardPage
	csilResp, csilErr := c.transport.Call(ctx, "board", "ListBoards", EncodeListBoardsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBoardPage(csilResp)
}

func (c *BoardClient) GetBoard(ctx context.Context, req BoardSlug) (Board, error) {
	var csilZero Board
	csilResp, csilErr := c.transport.Call(ctx, "board", "GetBoard", EncodeBoardGetBoardRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBoard(csilResp)
}

func (c *BoardClient) CreateBoard(ctx context.Context, req CreateBoardRequest) (Board, error) {
	var csilZero Board
	csilResp, csilErr := c.transport.Call(ctx, "board", "CreateBoard", EncodeCreateBoardRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBoard(csilResp)
}

func (c *BoardClient) UpdateBoard(ctx context.Context, req UpdateBoardRequest) (Board, error) {
	var csilZero Board
	csilResp, csilErr := c.transport.Call(ctx, "board", "UpdateBoard", EncodeUpdateBoardRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBoard(csilResp)
}

func (c *BoardClient) ArchiveBoard(ctx context.Context, req BoardID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "board", "ArchiveBoard", EncodeBoardArchiveBoardRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *BoardClient) SetBoardMember(ctx context.Context, req SetBoardMemberRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "board", "SetBoardMember", EncodeSetBoardMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *BoardClient) RemoveBoardMember(ctx context.Context, req RemoveBoardMemberRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "board", "RemoveBoardMember", EncodeRemoveBoardMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

// ThreadClient is a typed client for the ThreadService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ThreadClient struct {
	transport Transport
}

func NewThreadClient(transport Transport) *ThreadClient {
	return &ThreadClient{transport: transport}
}

func (c *ThreadClient) ListPosts(ctx context.Context, req ListPostsRequest) (PostPage, error) {
	var csilZero PostPage
	csilResp, csilErr := c.transport.Call(ctx, "thread", "ListPosts", EncodeListPostsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePostPage(csilResp)
}

func (c *ThreadClient) GetThread(ctx context.Context, req GetThreadRequest) (Thread, error) {
	var csilZero Thread
	csilResp, csilErr := c.transport.Call(ctx, "thread", "GetThread", EncodeGetThreadRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeThread(csilResp)
}

func (c *ThreadClient) CreatePost(ctx context.Context, req CreatePostRequest) (Post, error) {
	var csilZero Post
	csilResp, csilErr := c.transport.Call(ctx, "thread", "CreatePost", EncodeCreatePostRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePost(csilResp)
}

func (c *ThreadClient) CreateComment(ctx context.Context, req CreateCommentRequest) (Comment, error) {
	var csilZero Comment
	csilResp, csilErr := c.transport.Call(ctx, "thread", "CreateComment", EncodeCreateCommentRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeComment(csilResp)
}

func (c *ThreadClient) EditPost(ctx context.Context, req EditPostRequest) (Post, error) {
	var csilZero Post
	csilResp, csilErr := c.transport.Call(ctx, "thread", "EditPost", EncodeEditPostRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePost(csilResp)
}

func (c *ThreadClient) EditComment(ctx context.Context, req EditCommentRequest) (Comment, error) {
	var csilZero Comment
	csilResp, csilErr := c.transport.Call(ctx, "thread", "EditComment", EncodeEditCommentRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeComment(csilResp)
}

func (c *ThreadClient) ListRevisions(ctx context.Context, req TargetRef) (RevisionList, error) {
	var csilZero RevisionList
	csilResp, csilErr := c.transport.Call(ctx, "thread", "ListRevisions", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRevisionList(csilResp)
}

func (c *ThreadClient) DeletePost(ctx context.Context, req PostID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "thread", "DeletePost", EncodeThreadDeletePostRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *ThreadClient) DeleteComment(ctx context.Context, req CommentID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "thread", "DeleteComment", EncodeThreadDeleteCommentRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

// EndorsementClient is a typed client for the EndorsementService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type EndorsementClient struct {
	transport Transport
}

func NewEndorsementClient(transport Transport) *EndorsementClient {
	return &EndorsementClient{transport: transport}
}

func (c *EndorsementClient) Endorse(ctx context.Context, req EndorseRequest) (Endorsement, error) {
	var csilZero Endorsement
	csilResp, csilErr := c.transport.Call(ctx, "endorsement", "Endorse", EncodeEndorseRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEndorsement(csilResp)
}

func (c *EndorsementClient) Retract(ctx context.Context, req EndorseRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "endorsement", "Retract", EncodeEndorseRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *EndorsementClient) ListEndorsements(ctx context.Context, req TargetRef) (EndorsementList, error) {
	var csilZero EndorsementList
	csilResp, csilErr := c.transport.Call(ctx, "endorsement", "ListEndorsements", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEndorsementList(csilResp)
}

// SettingsClient is a typed client for the SettingsService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SettingsClient struct {
	transport Transport
}

func NewSettingsClient(transport Transport) *SettingsClient {
	return &SettingsClient{transport: transport}
}

func (c *SettingsClient) GetSettings(ctx context.Context, req Empty) (UserSettings, error) {
	var csilZero UserSettings
	csilResp, csilErr := c.transport.Call(ctx, "settings", "GetSettings", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserSettings(csilResp)
}

func (c *SettingsClient) UpdateSettings(ctx context.Context, req UpdateSettingsRequest) (UserSettings, error) {
	var csilZero UserSettings
	csilResp, csilErr := c.transport.Call(ctx, "settings", "UpdateSettings", EncodeUpdateSettingsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserSettings(csilResp)
}

func (c *SettingsClient) ListMentionGrants(ctx context.Context, req Empty) (MentionGrantList, error) {
	var csilZero MentionGrantList
	csilResp, csilErr := c.transport.Call(ctx, "settings", "ListMentionGrants", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMentionGrantList(csilResp)
}

func (c *SettingsClient) GrantMention(ctx context.Context, req UserID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "settings", "GrantMention", EncodeSettingsGrantMentionRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *SettingsClient) RevokeMention(ctx context.Context, req UserID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "settings", "RevokeMention", EncodeSettingsRevokeMentionRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

// SocialClient is a typed client for the SocialService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SocialClient struct {
	transport Transport
}

func NewSocialClient(transport Transport) *SocialClient {
	return &SocialClient{transport: transport}
}

func (c *SocialClient) ListFriendGroups(ctx context.Context, req Empty) (FriendGroupList, error) {
	var csilZero FriendGroupList
	csilResp, csilErr := c.transport.Call(ctx, "social", "ListFriendGroups", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeFriendGroupList(csilResp)
}

func (c *SocialClient) CreateFriendGroup(ctx context.Context, req CreateFriendGroupRequest) (FriendGroup, error) {
	var csilZero FriendGroup
	csilResp, csilErr := c.transport.Call(ctx, "social", "CreateFriendGroup", EncodeCreateFriendGroupRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeFriendGroup(csilResp)
}

func (c *SocialClient) DeleteFriendGroup(ctx context.Context, req GroupID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "social", "DeleteFriendGroup", EncodeSocialDeleteFriendGroupRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *SocialClient) AddFriend(ctx context.Context, req AddFriendRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "social", "AddFriend", EncodeAddFriendRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *SocialClient) RemoveFriend(ctx context.Context, req RemoveFriendRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "social", "RemoveFriend", EncodeRemoveFriendRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *SocialClient) ResolveUser(ctx context.Context, req Handle) (UserProfile, error) {
	var csilZero UserProfile
	csilResp, csilErr := c.transport.Call(ctx, "social", "ResolveUser", EncodeSocialResolveUserRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserProfile(csilResp)
}

// SubscriptionClient is a typed client for the SubscriptionService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SubscriptionClient struct {
	transport Transport
}

func NewSubscriptionClient(transport Transport) *SubscriptionClient {
	return &SubscriptionClient{transport: transport}
}

func (c *SubscriptionClient) Subscribe(ctx context.Context, req TargetRef) (Subscription, error) {
	var csilZero Subscription
	csilResp, csilErr := c.transport.Call(ctx, "subscription", "Subscribe", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSubscription(csilResp)
}

func (c *SubscriptionClient) Unsubscribe(ctx context.Context, req TargetRef) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "subscription", "Unsubscribe", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *SubscriptionClient) SetMuted(ctx context.Context, req SetMutedRequest) (Subscription, error) {
	var csilZero Subscription
	csilResp, csilErr := c.transport.Call(ctx, "subscription", "SetMuted", EncodeSetMutedRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSubscription(csilResp)
}

func (c *SubscriptionClient) ListSubscriptions(ctx context.Context, req Empty) (SubscriptionList, error) {
	var csilZero SubscriptionList
	csilResp, csilErr := c.transport.Call(ctx, "subscription", "ListSubscriptions", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSubscriptionList(csilResp)
}

// ReadClient is a typed client for the ReadService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ReadClient struct {
	transport Transport
}

func NewReadClient(transport Transport) *ReadClient {
	return &ReadClient{transport: transport}
}

func (c *ReadClient) MarkRead(ctx context.Context, req TargetRef) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "read", "MarkRead", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *ReadClient) MarkUnread(ctx context.Context, req TargetRef) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "read", "MarkUnread", EncodeTargetRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *ReadClient) UnreadSummary(ctx context.Context, req Empty) (UnreadSummary, error) {
	var csilZero UnreadSummary
	csilResp, csilErr := c.transport.Call(ctx, "read", "UnreadSummary", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUnreadSummary(csilResp)
}

// NotificationClient is a typed client for the NotificationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type NotificationClient struct {
	transport Transport
}

func NewNotificationClient(transport Transport) *NotificationClient {
	return &NotificationClient{transport: transport}
}

func (c *NotificationClient) ListNotifications(ctx context.Context, req ListNotificationsRequest) (NotificationPage, error) {
	var csilZero NotificationPage
	csilResp, csilErr := c.transport.Call(ctx, "notification", "ListNotifications", EncodeListNotificationsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeNotificationPage(csilResp)
}

func (c *NotificationClient) MarkNotificationRead(ctx context.Context, req NotificationIDs) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "notification", "MarkNotificationRead", EncodeNotificationMarkNotificationReadRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *NotificationClient) MarkAllRead(ctx context.Context, req Empty) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "notification", "MarkAllRead", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

// IntegrationClient is a typed client for the IntegrationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type IntegrationClient struct {
	transport Transport
}

func NewIntegrationClient(transport Transport) *IntegrationClient {
	return &IntegrationClient{transport: transport}
}

func (c *IntegrationClient) CreateGithubMapping(ctx context.Context, req CreateMappingRequest) (GithubMapping, error) {
	var csilZero GithubMapping
	csilResp, csilErr := c.transport.Call(ctx, "integration", "CreateGithubMapping", EncodeCreateMappingRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGithubMapping(csilResp)
}

func (c *IntegrationClient) ListGithubMappings(ctx context.Context, req Empty) (MappingList, error) {
	var csilZero MappingList
	csilResp, csilErr := c.transport.Call(ctx, "integration", "ListGithubMappings", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMappingList(csilResp)
}

func (c *IntegrationClient) DeleteGithubMapping(ctx context.Context, req MappingID) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "integration", "DeleteGithubMapping", EncodeIntegrationDeleteGithubMappingRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *IntegrationClient) AddTrustedDomain(ctx context.Context, req Domain) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "integration", "AddTrustedDomain", EncodeIntegrationAddTrustedDomainRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *IntegrationClient) RemoveTrustedDomain(ctx context.Context, req Domain) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "integration", "RemoveTrustedDomain", EncodeIntegrationRemoveTrustedDomainRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *IntegrationClient) ListTrustedDomains(ctx context.Context, req Empty) (DomainList, error) {
	var csilZero DomainList
	csilResp, csilErr := c.transport.Call(ctx, "integration", "ListTrustedDomains", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDomainList(csilResp)
}
