// Package firepitclient contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package firepitclient

import (
	"context"
)

// AuthService defines the service interface
type AuthService interface {
	BeginLogin(ctx context.Context, req BeginLoginRequest) (BeginLoginResponse, error)
	Logout(ctx context.Context, req Empty) (Empty, error)
	Whoami(ctx context.Context, req Empty) (UserProfile, error)
}

// Wire-id ordinals for the AuthService service (transport compact profiles).
const AuthServiceServiceWireID uint64 = 1
const AuthServiceOpBeginLoginWireID uint64 = 0
const AuthServiceOpLogoutWireID uint64 = 1
const AuthServiceOpWhoamiWireID uint64 = 2

// BoardService defines the service interface
type BoardService interface {
	ListBoards(ctx context.Context, req ListBoardsRequest) (BoardPage, error)
	GetBoard(ctx context.Context, req BoardSlug) (Board, error)
	CreateBoard(ctx context.Context, req CreateBoardRequest) (Board, error)
	UpdateBoard(ctx context.Context, req UpdateBoardRequest) (Board, error)
	ArchiveBoard(ctx context.Context, req BoardID) (Empty, error)
	SetBoardMember(ctx context.Context, req SetBoardMemberRequest) (Empty, error)
	RemoveBoardMember(ctx context.Context, req RemoveBoardMemberRequest) (Empty, error)
}

// Wire-id ordinals for the BoardService service (transport compact profiles).
const BoardServiceServiceWireID uint64 = 2
const BoardServiceOpListBoardsWireID uint64 = 0
const BoardServiceOpGetBoardWireID uint64 = 1
const BoardServiceOpCreateBoardWireID uint64 = 2
const BoardServiceOpUpdateBoardWireID uint64 = 3
const BoardServiceOpArchiveBoardWireID uint64 = 4
const BoardServiceOpSetBoardMemberWireID uint64 = 5
const BoardServiceOpRemoveBoardMemberWireID uint64 = 6

// ThreadService defines the service interface
type ThreadService interface {
	ListPosts(ctx context.Context, req ListPostsRequest) (PostPage, error)
	GetThread(ctx context.Context, req GetThreadRequest) (Thread, error)
	CreatePost(ctx context.Context, req CreatePostRequest) (Post, error)
	CreateComment(ctx context.Context, req CreateCommentRequest) (Comment, error)
	EditPost(ctx context.Context, req EditPostRequest) (Post, error)
	EditComment(ctx context.Context, req EditCommentRequest) (Comment, error)
	ListRevisions(ctx context.Context, req TargetRef) (RevisionList, error)
	DeletePost(ctx context.Context, req PostID) (Empty, error)
	DeleteComment(ctx context.Context, req CommentID) (Empty, error)
}

// Wire-id ordinals for the ThreadService service (transport compact profiles).
const ThreadServiceServiceWireID uint64 = 3
const ThreadServiceOpListPostsWireID uint64 = 0
const ThreadServiceOpGetThreadWireID uint64 = 1
const ThreadServiceOpCreatePostWireID uint64 = 2
const ThreadServiceOpCreateCommentWireID uint64 = 3
const ThreadServiceOpEditPostWireID uint64 = 4
const ThreadServiceOpEditCommentWireID uint64 = 5
const ThreadServiceOpListRevisionsWireID uint64 = 6
const ThreadServiceOpDeletePostWireID uint64 = 7
const ThreadServiceOpDeleteCommentWireID uint64 = 8

// EndorsementService defines the service interface
type EndorsementService interface {
	Endorse(ctx context.Context, req EndorseRequest) (Endorsement, error)
	Retract(ctx context.Context, req EndorseRequest) (Empty, error)
	ListEndorsements(ctx context.Context, req TargetRef) (EndorsementList, error)
}

// Wire-id ordinals for the EndorsementService service (transport compact profiles).
const EndorsementServiceServiceWireID uint64 = 4
const EndorsementServiceOpEndorseWireID uint64 = 0
const EndorsementServiceOpRetractWireID uint64 = 1
const EndorsementServiceOpListEndorsementsWireID uint64 = 2

// SettingsService defines the service interface
type SettingsService interface {
	GetSettings(ctx context.Context, req Empty) (UserSettings, error)
	UpdateSettings(ctx context.Context, req UpdateSettingsRequest) (UserSettings, error)
	ListMentionGrants(ctx context.Context, req Empty) (MentionGrantList, error)
	GrantMention(ctx context.Context, req UserID) (Empty, error)
	RevokeMention(ctx context.Context, req UserID) (Empty, error)
}

// Wire-id ordinals for the SettingsService service (transport compact profiles).
const SettingsServiceServiceWireID uint64 = 5
const SettingsServiceOpGetSettingsWireID uint64 = 0
const SettingsServiceOpUpdateSettingsWireID uint64 = 1
const SettingsServiceOpListMentionGrantsWireID uint64 = 2
const SettingsServiceOpGrantMentionWireID uint64 = 3
const SettingsServiceOpRevokeMentionWireID uint64 = 4

// SocialService defines the service interface
type SocialService interface {
	ListFriendGroups(ctx context.Context, req Empty) (FriendGroupList, error)
	CreateFriendGroup(ctx context.Context, req CreateFriendGroupRequest) (FriendGroup, error)
	DeleteFriendGroup(ctx context.Context, req GroupID) (Empty, error)
	AddFriend(ctx context.Context, req AddFriendRequest) (Empty, error)
	RemoveFriend(ctx context.Context, req RemoveFriendRequest) (Empty, error)
	ResolveUser(ctx context.Context, req Handle) (UserProfile, error)
}

// Wire-id ordinals for the SocialService service (transport compact profiles).
const SocialServiceServiceWireID uint64 = 6
const SocialServiceOpListFriendGroupsWireID uint64 = 0
const SocialServiceOpCreateFriendGroupWireID uint64 = 1
const SocialServiceOpDeleteFriendGroupWireID uint64 = 2
const SocialServiceOpAddFriendWireID uint64 = 3
const SocialServiceOpRemoveFriendWireID uint64 = 4
const SocialServiceOpResolveUserWireID uint64 = 5

// SubscriptionService defines the service interface
type SubscriptionService interface {
	Subscribe(ctx context.Context, req TargetRef) (Subscription, error)
	Unsubscribe(ctx context.Context, req TargetRef) (Empty, error)
	SetMuted(ctx context.Context, req SetMutedRequest) (Subscription, error)
	ListSubscriptions(ctx context.Context, req Empty) (SubscriptionList, error)
}

// Wire-id ordinals for the SubscriptionService service (transport compact profiles).
const SubscriptionServiceServiceWireID uint64 = 7
const SubscriptionServiceOpSubscribeWireID uint64 = 0
const SubscriptionServiceOpUnsubscribeWireID uint64 = 1
const SubscriptionServiceOpSetMutedWireID uint64 = 2
const SubscriptionServiceOpListSubscriptionsWireID uint64 = 3

// ReadService defines the service interface
type ReadService interface {
	MarkRead(ctx context.Context, req TargetRef) (Empty, error)
	MarkUnread(ctx context.Context, req TargetRef) (Empty, error)
	UnreadSummary(ctx context.Context, req Empty) (UnreadSummary, error)
}

// Wire-id ordinals for the ReadService service (transport compact profiles).
const ReadServiceServiceWireID uint64 = 8
const ReadServiceOpMarkReadWireID uint64 = 0
const ReadServiceOpMarkUnreadWireID uint64 = 1
const ReadServiceOpUnreadSummaryWireID uint64 = 2

// NotificationService defines the service interface
type NotificationService interface {
	ListNotifications(ctx context.Context, req ListNotificationsRequest) (NotificationPage, error)
	MarkNotificationRead(ctx context.Context, req NotificationIDs) (Empty, error)
	MarkAllRead(ctx context.Context, req Empty) (Empty, error)
}

// Wire-id ordinals for the NotificationService service (transport compact profiles).
const NotificationServiceServiceWireID uint64 = 9
const NotificationServiceOpListNotificationsWireID uint64 = 0
const NotificationServiceOpMarkNotificationReadWireID uint64 = 1
const NotificationServiceOpMarkAllReadWireID uint64 = 2

// IntegrationService defines the service interface
type IntegrationService interface {
	CreateGithubMapping(ctx context.Context, req CreateMappingRequest) (GithubMapping, error)
	ListGithubMappings(ctx context.Context, req Empty) (MappingList, error)
	DeleteGithubMapping(ctx context.Context, req MappingID) (Empty, error)
	AddTrustedDomain(ctx context.Context, req Domain) (Empty, error)
	RemoveTrustedDomain(ctx context.Context, req Domain) (Empty, error)
	ListTrustedDomains(ctx context.Context, req Empty) (DomainList, error)
}

// Wire-id ordinals for the IntegrationService service (transport compact profiles).
const IntegrationServiceServiceWireID uint64 = 10
const IntegrationServiceOpCreateGithubMappingWireID uint64 = 0
const IntegrationServiceOpListGithubMappingsWireID uint64 = 1
const IntegrationServiceOpDeleteGithubMappingWireID uint64 = 2
const IntegrationServiceOpAddTrustedDomainWireID uint64 = 3
const IntegrationServiceOpRemoveTrustedDomainWireID uint64 = 4
const IntegrationServiceOpListTrustedDomainsWireID uint64 = 5
