{{- if and .Values.linkkeysRp.enabled .Values.linkkeysRp.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "firepit.fullname" . }}-linkkeys-rp-data
  labels:
    {{- include "firepit.labels" . | nindent 4 }}
    app.kubernetes.io/component: linkkeys-rp
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.linkkeysRp.persistence.storageClassName }}
  storageClassName: {{ .Values.linkkeysRp.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.linkkeysRp.persistence.size }}
{{- end }}
