// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-client

import type { AddFriendRequest, AuthError, BeginLoginRequest, BeginLoginResponse, Board, BoardID, BoardPage, BoardSlug, Comment, CommentID, CreateBoardRequest, CreateCommentRequest, CreateFriendGroupRequest, CreateMappingRequest, CreatePostRequest, Domain, DomainList, EditCommentRequest, EditPostRequest, Empty, EndorseRequest, Endorsement, EndorsementList, FirepitError, FriendGroup, FriendGroupList, GetThreadRequest, GithubMapping, GroupID, ListBoardsRequest, ListNotificationsRequest, ListPostsRequest, MappingID, MappingList, MentionGrantList, NotFoundError, NotificationIDs, NotificationPage, Post, PostID, PostPage, RemoveBoardMemberRequest, RemoveFriendRequest, RevisionList, SetBoardMemberRequest, SetMutedRequest, Subscription, SubscriptionList, TargetRef, Thread, UnreadSummary, UpdateBoardRequest, UpdateSettingsRequest, UserID, UserProfile, UserSettings } from "./types.gen";
import { encodeValue, fromBoardPageCbor, fromDomainListCbor, fromEmptyCbor, fromEndorsementListCbor, fromFriendGroupListCbor, fromMappingListCbor, fromMentionGrantListCbor, fromNotificationPageCbor, fromPostPageCbor, fromRevisionListCbor, fromSubscriptionListCbor, fromThreadCbor, fromUnreadSummaryCbor, fromUserSettingsCbor, toEmptyCbor, toGetThreadRequestCbor, toListBoardsRequestCbor, toListNotificationsRequestCbor, toListPostsRequestCbor, toTargetRefCbor } from "./codec.gen";

export interface ServiceTransport {
  call(service: string, op: string, req: Uint8Array): Uint8Array;
}

export class AuthClient {
  constructor(private readonly t: ServiceTransport) {}


  // operation 'begin-login' has a non-record payload; (de)serialize it manually

  /**
   * Clear the caller's session cookie. Idempotent; never errors even if
   * already logged out.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  logout(req: Empty): Empty {
    const csilResp = this.t.call("auth", "Logout", toEmptyCbor(req));
    return fromEmptyCbor(csilResp);
  }


  // operation 'whoami' has a non-record payload; (de)serialize it manually
}

export class BoardClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Cursor-paginated listing of all boards, ordered by title.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listBoards(req: ListBoardsRequest): BoardPage {
    const csilResp = this.t.call("board", "ListBoards", toListBoardsRequestCbor(req));
    return fromBoardPageCbor(csilResp);
  }


  // operation 'get-board' has a non-record payload; (de)serialize it manually


  // operation 'create-board' has a non-record payload; (de)serialize it manually


  // operation 'update-board' has a non-record payload; (de)serialize it manually


  // operation 'archive-board' has a non-record payload; (de)serialize it manually


  // operation 'set-board-member' has a non-record payload; (de)serialize it manually


  // operation 'remove-board-member' has a non-record payload; (de)serialize it manually
}

export class EndorsementClient {
  constructor(private readonly t: ServiceTransport) {}


  // operation 'endorse' has a non-record payload; (de)serialize it manually


  // operation 'retract' has a non-record payload; (de)serialize it manually

  /**
   * The full endorser list for a target, pre-ordered per-viewer by the
   * server (friends first, then reputation).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listEndorsements(req: TargetRef): EndorsementList {
    const csilResp = this.t.call("endorsement", "ListEndorsements", toTargetRefCbor(req));
    return fromEndorsementListCbor(csilResp);
  }
}

export class IntegrationClient {
  constructor(private readonly t: ServiceTransport) {}


  // operation 'create-github-mapping' has a non-record payload; (de)serialize it manually

  /**
   * All configured GitHub mappings.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listGithubMappings(req: Empty): MappingList {
    const csilResp = this.t.call("integration", "ListGithubMappings", toEmptyCbor(req));
    return fromMappingListCbor(csilResp);
  }


  // operation 'delete-github-mapping' has a non-record payload; (de)serialize it manually


  // operation 'add-trusted-domain' has a non-record payload; (de)serialize it manually


  // operation 'remove-trusted-domain' has a non-record payload; (de)serialize it manually

  /**
   * All trusted domains.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listTrustedDomains(req: Empty): DomainList {
    const csilResp = this.t.call("integration", "ListTrustedDomains", toEmptyCbor(req));
    return fromDomainListCbor(csilResp);
  }
}

export class NotificationClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Cursor-paginated notification inbox, newest first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listNotifications(req: ListNotificationsRequest): NotificationPage {
    const csilResp = this.t.call("notification", "ListNotifications", toListNotificationsRequestCbor(req));
    return fromNotificationPageCbor(csilResp);
  }

  /**
   * Mark a specific set of notifications read.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markNotificationRead(req: NotificationIDs): Empty {
    const csilResp = this.t.call("notification", "MarkNotificationRead", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Mark every one of the caller's notifications read.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markAllRead(req: Empty): Empty {
    const csilResp = this.t.call("notification", "MarkAllRead", toEmptyCbor(req));
    return fromEmptyCbor(csilResp);
  }
}

export class ReadClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Mark an item (or a whole post) read: advances the watermark and/or
   * clears any unread override pinning it unread.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markRead(req: TargetRef): Empty {
    const csilResp = this.t.call("read", "MarkRead", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Pin an item unread regardless of the watermark, until it's
   * explicitly mark-read again.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markUnread(req: TargetRef): Empty {
    const csilResp = this.t.call("read", "MarkUnread", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Per-board/post unread counts for the caller — the poll endpoint the
   * UI hits to drive unread badges.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  unreadSummary(req: Empty): UnreadSummary {
    const csilResp = this.t.call("read", "UnreadSummary", toEmptyCbor(req));
    return fromUnreadSummaryCbor(csilResp);
  }
}

export class SettingsClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * The caller's own settings (defaults filled in).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  getSettings(req: Empty): UserSettings {
    const csilResp = this.t.call("settings", "GetSettings", toEmptyCbor(req));
    return fromUserSettingsCbor(csilResp);
  }


  // operation 'update-settings' has a non-record payload; (de)serialize it manually

  /**
   * Users the caller has granted permanent mention-notify permission to.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listMentionGrants(req: Empty): MentionGrantList {
    const csilResp = this.t.call("settings", "ListMentionGrants", toEmptyCbor(req));
    return fromMentionGrantListCbor(csilResp);
  }


  // operation 'grant-mention' has a non-record payload; (de)serialize it manually


  // operation 'revoke-mention' has a non-record payload; (de)serialize it manually
}

export class SocialClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * The caller's own friend groups and their membership.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listFriendGroups(req: Empty): FriendGroupList {
    const csilResp = this.t.call("social", "ListFriendGroups", toEmptyCbor(req));
    return fromFriendGroupListCbor(csilResp);
  }


  // operation 'create-friend-group' has a non-record payload; (de)serialize it manually


  // operation 'delete-friend-group' has a non-record payload; (de)serialize it manually


  // operation 'add-friend' has a non-record payload; (de)serialize it manually


  // operation 'remove-friend' has a non-record payload; (de)serialize it manually
}

export class SubscriptionClient {
  constructor(private readonly t: ServiceTransport) {}


  // operation 'subscribe' has a non-record payload; (de)serialize it manually


  // operation 'unsubscribe' has a non-record payload; (de)serialize it manually


  // operation 'set-muted' has a non-record payload; (de)serialize it manually

  /**
   * All of the caller's subscriptions.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listSubscriptions(req: Empty): SubscriptionList {
    const csilResp = this.t.call("subscription", "ListSubscriptions", toEmptyCbor(req));
    return fromSubscriptionListCbor(csilResp);
  }
}

export class ThreadClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Cursor-paginated listing of a board's posts, newest activity first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listPosts(req: ListPostsRequest): PostPage {
    const csilResp = this.t.call("thread", "ListPosts", toListPostsRequestCbor(req));
    return fromPostPageCbor(csilResp);
  }

  /**
   * The full post plus its whole comment tree, depth-first ordered.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  getThread(req: GetThreadRequest): Thread {
    const csilResp = this.t.call("thread", "GetThread", toGetThreadRequestCbor(req));
    return fromThreadCbor(csilResp);
  }


  // operation 'create-post' has a non-record payload; (de)serialize it manually


  // operation 'create-comment' has a non-record payload; (de)serialize it manually


  // operation 'edit-post' has a non-record payload; (de)serialize it manually


  // operation 'edit-comment' has a non-record payload; (de)serialize it manually

  /**
   * Full edit history for a post or comment, newest first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listRevisions(req: TargetRef): RevisionList {
    const csilResp = this.t.call("thread", "ListRevisions", toTargetRefCbor(req));
    return fromRevisionListCbor(csilResp);
  }


  // operation 'delete-post' has a non-record payload; (de)serialize it manually


  // operation 'delete-comment' has a non-record payload; (de)serialize it manually
}

export class ApiClient {
  readonly auth: AuthClient;
  readonly board: BoardClient;
  readonly endorsement: EndorsementClient;
  readonly integration: IntegrationClient;
  readonly notification: NotificationClient;
  readonly read: ReadClient;
  readonly settings: SettingsClient;
  readonly social: SocialClient;
  readonly subscription: SubscriptionClient;
  readonly thread: ThreadClient;
  constructor(t: ServiceTransport) {
    this.auth = new AuthClient(t);
    this.board = new BoardClient(t);
    this.endorsement = new EndorsementClient(t);
    this.integration = new IntegrationClient(t);
    this.notification = new NotificationClient(t);
    this.read = new ReadClient(t);
    this.settings = new SettingsClient(t);
    this.social = new SocialClient(t);
    this.subscription = new SubscriptionClient(t);
    this.thread = new ThreadClient(t);
  }
}
