// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-client

import type { AddFriendRequest, AuthError, BeginLoginRequest, BeginLoginResponse, Board, BoardID, BoardPage, BoardSlug, Comment, CommentID, CreateBoardRequest, CreateCommentRequest, CreateFriendGroupRequest, CreateMappingRequest, CreatePostRequest, Domain, DomainList, EditCommentRequest, EditPostRequest, Empty, EndorseRequest, Endorsement, EndorsementList, FirepitError, FriendGroup, FriendGroupList, GetThreadRequest, GithubMapping, GroupID, ListBoardsRequest, ListNotificationsRequest, ListPostsRequest, MappingID, MappingList, MentionGrantList, NotFoundError, NotificationIDs, NotificationPage, Post, PostID, PostPage, RemoveBoardMemberRequest, RemoveFriendRequest, RevisionList, SetBoardMemberRequest, SetMutedRequest, Subscription, SubscriptionList, TargetRef, Thread, UnreadSummary, UpdateBoardRequest, UpdateSettingsRequest, UserID, UserProfile, UserSettings } from "./types.gen";
import { encodeValue, fromBoardPageCbor, fromDomainListCbor, fromEmptyCbor, fromEndorsementListCbor, fromFriendGroupListCbor, fromMappingListCbor, fromMentionGrantListCbor, fromNotificationPageCbor, fromPostPageCbor, fromRevisionListCbor, fromSubscriptionListCbor, fromThreadCbor, fromUnreadSummaryCbor, fromUserSettingsCbor, toEmptyCbor, toGetThreadRequestCbor, toListBoardsRequestCbor, toListNotificationsRequestCbor, toListPostsRequestCbor, toTargetRefCbor } from "./codec.gen";

export interface AsyncServiceTransport {
  call(service: string, op: string, req: Uint8Array): Promise<Uint8Array>;
}

export class AuthAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}


  // operation 'begin-login' has a non-record payload; (de)serialize it manually

  /**
   * Clear the caller's session cookie. Idempotent; never errors even if
   * already logged out.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async logout(req: Empty): Promise<Empty> {
    const csilResp = await this.t.call("auth", "Logout", toEmptyCbor(req));
    return fromEmptyCbor(csilResp);
  }


  // operation 'whoami' has a non-record payload; (de)serialize it manually
}

export class BoardAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * Cursor-paginated listing of all boards, ordered by title.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listBoards(req: ListBoardsRequest): Promise<BoardPage> {
    const csilResp = await this.t.call("board", "ListBoards", toListBoardsRequestCbor(req));
    return fromBoardPageCbor(csilResp);
  }


  // operation 'get-board' has a non-record payload; (de)serialize it manually


  // operation 'create-board' has a non-record payload; (de)serialize it manually


  // operation 'update-board' has a non-record payload; (de)serialize it manually


  // operation 'archive-board' has a non-record payload; (de)serialize it manually


  // operation 'set-board-member' has a non-record payload; (de)serialize it manually


  // operation 'remove-board-member' has a non-record payload; (de)serialize it manually
}

export class EndorsementAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}


  // operation 'endorse' has a non-record payload; (de)serialize it manually


  // operation 'retract' has a non-record payload; (de)serialize it manually

  /**
   * The full endorser list for a target, pre-ordered per-viewer by the
   * server (friends first, then reputation).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listEndorsements(req: TargetRef): Promise<EndorsementList> {
    const csilResp = await this.t.call("endorsement", "ListEndorsements", toTargetRefCbor(req));
    return fromEndorsementListCbor(csilResp);
  }
}

export class IntegrationAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}


  // operation 'create-github-mapping' has a non-record payload; (de)serialize it manually

  /**
   * All configured GitHub mappings.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listGithubMappings(req: Empty): Promise<MappingList> {
    const csilResp = await this.t.call("integration", "ListGithubMappings", toEmptyCbor(req));
    return fromMappingListCbor(csilResp);
  }


  // operation 'delete-github-mapping' has a non-record payload; (de)serialize it manually


  // operation 'add-trusted-domain' has a non-record payload; (de)serialize it manually


  // operation 'remove-trusted-domain' has a non-record payload; (de)serialize it manually

  /**
   * All trusted domains.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listTrustedDomains(req: Empty): Promise<DomainList> {
    const csilResp = await this.t.call("integration", "ListTrustedDomains", toEmptyCbor(req));
    return fromDomainListCbor(csilResp);
  }
}

export class NotificationAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * Cursor-paginated notification inbox, newest first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listNotifications(req: ListNotificationsRequest): Promise<NotificationPage> {
    const csilResp = await this.t.call("notification", "ListNotifications", toListNotificationsRequestCbor(req));
    return fromNotificationPageCbor(csilResp);
  }

  /**
   * Mark a specific set of notifications read.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async markNotificationRead(req: NotificationIDs): Promise<Empty> {
    const csilResp = await this.t.call("notification", "MarkNotificationRead", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Mark every one of the caller's notifications read.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async markAllRead(req: Empty): Promise<Empty> {
    const csilResp = await this.t.call("notification", "MarkAllRead", toEmptyCbor(req));
    return fromEmptyCbor(csilResp);
  }
}

export class ReadAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * Mark an item (or a whole post) read: advances the watermark and/or
   * clears any unread override pinning it unread.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async markRead(req: TargetRef): Promise<Empty> {
    const csilResp = await this.t.call("read", "MarkRead", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Pin an item unread regardless of the watermark, until it's
   * explicitly mark-read again.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async markUnread(req: TargetRef): Promise<Empty> {
    const csilResp = await this.t.call("read", "MarkUnread", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Per-board/post unread counts for the caller — the poll endpoint the
   * UI hits to drive unread badges.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async unreadSummary(req: Empty): Promise<UnreadSummary> {
    const csilResp = await this.t.call("read", "UnreadSummary", toEmptyCbor(req));
    return fromUnreadSummaryCbor(csilResp);
  }
}

export class SettingsAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * The caller's own settings (defaults filled in).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getSettings(req: Empty): Promise<UserSettings> {
    const csilResp = await this.t.call("settings", "GetSettings", toEmptyCbor(req));
    return fromUserSettingsCbor(csilResp);
  }


  // operation 'update-settings' has a non-record payload; (de)serialize it manually

  /**
   * Users the caller has granted permanent mention-notify permission to.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listMentionGrants(req: Empty): Promise<MentionGrantList> {
    const csilResp = await this.t.call("settings", "ListMentionGrants", toEmptyCbor(req));
    return fromMentionGrantListCbor(csilResp);
  }


  // operation 'grant-mention' has a non-record payload; (de)serialize it manually


  // operation 'revoke-mention' has a non-record payload; (de)serialize it manually
}

export class SocialAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * The caller's own friend groups and their membership.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listFriendGroups(req: Empty): Promise<FriendGroupList> {
    const csilResp = await this.t.call("social", "ListFriendGroups", toEmptyCbor(req));
    return fromFriendGroupListCbor(csilResp);
  }


  // operation 'create-friend-group' has a non-record payload; (de)serialize it manually


  // operation 'delete-friend-group' has a non-record payload; (de)serialize it manually


  // operation 'add-friend' has a non-record payload; (de)serialize it manually


  // operation 'remove-friend' has a non-record payload; (de)serialize it manually
}

export class SubscriptionAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}


  // operation 'subscribe' has a non-record payload; (de)serialize it manually


  // operation 'unsubscribe' has a non-record payload; (de)serialize it manually


  // operation 'set-muted' has a non-record payload; (de)serialize it manually

  /**
   * All of the caller's subscriptions.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listSubscriptions(req: Empty): Promise<SubscriptionList> {
    const csilResp = await this.t.call("subscription", "ListSubscriptions", toEmptyCbor(req));
    return fromSubscriptionListCbor(csilResp);
  }
}

export class ThreadAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * Cursor-paginated listing of a board's posts, newest activity first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listPosts(req: ListPostsRequest): Promise<PostPage> {
    const csilResp = await this.t.call("thread", "ListPosts", toListPostsRequestCbor(req));
    return fromPostPageCbor(csilResp);
  }

  /**
   * The full post plus its whole comment tree, depth-first ordered.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getThread(req: GetThreadRequest): Promise<Thread> {
    const csilResp = await this.t.call("thread", "GetThread", toGetThreadRequestCbor(req));
    return fromThreadCbor(csilResp);
  }


  // operation 'create-post' has a non-record payload; (de)serialize it manually


  // operation 'create-comment' has a non-record payload; (de)serialize it manually


  // operation 'edit-post' has a non-record payload; (de)serialize it manually


  // operation 'edit-comment' has a non-record payload; (de)serialize it manually

  /**
   * Full edit history for a post or comment, newest first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async listRevisions(req: TargetRef): Promise<RevisionList> {
    const csilResp = await this.t.call("thread", "ListRevisions", toTargetRefCbor(req));
    return fromRevisionListCbor(csilResp);
  }


  // operation 'delete-post' has a non-record payload; (de)serialize it manually


  // operation 'delete-comment' has a non-record payload; (de)serialize it manually
}

export class AsyncApiClient {
  readonly auth: AuthAsyncClient;
  readonly board: BoardAsyncClient;
  readonly endorsement: EndorsementAsyncClient;
  readonly integration: IntegrationAsyncClient;
  readonly notification: NotificationAsyncClient;
  readonly read: ReadAsyncClient;
  readonly settings: SettingsAsyncClient;
  readonly social: SocialAsyncClient;
  readonly subscription: SubscriptionAsyncClient;
  readonly thread: ThreadAsyncClient;
  constructor(t: AsyncServiceTransport) {
    this.auth = new AuthAsyncClient(t);
    this.board = new BoardAsyncClient(t);
    this.endorsement = new EndorsementAsyncClient(t);
    this.integration = new IntegrationAsyncClient(t);
    this.notification = new NotificationAsyncClient(t);
    this.read = new ReadAsyncClient(t);
    this.settings = new SettingsAsyncClient(t);
    this.social = new SocialAsyncClient(t);
    this.subscription = new SubscriptionAsyncClient(t);
    this.thread = new ThreadAsyncClient(t);
  }
}
