// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-client

import type { AddFriendRequest, BeginLoginRequest, BeginLoginResponse, Board, BoardID, BoardPage, BoardSlug, Category, CategoryList, Comment, CommentID, CreateBoardRequest, CreateCategoryRequest, CreateCommentRequest, CreateFriendGroupRequest, CreateMappingRequest, CreatePostRequest, DeleteCategoryRequest, Domain, DomainList, EditCommentRequest, EditPostRequest, Empty, EndorseRequest, Endorsement, EndorsementList, FriendGroup, FriendGroupList, GetThreadRequest, GithubMapping, GroupID, Handle, ListBoardsRequest, ListNotificationsRequest, ListPostsRequest, MappingID, MappingList, MentionGrantList, NotificationIDs, NotificationPage, Post, PostID, PostPage, RemoveBoardMemberRequest, RemoveFriendRequest, RevisionList, SetBoardMemberRequest, SetMutedRequest, Subscription, SubscriptionList, TargetRef, Thread, UnreadSummary, UpdateBoardRequest, UpdateCategoryRequest, UpdateSettingsRequest, UserID, UserProfile, UserSettings } from "./types.gen.ts";
import { encodeValue, fromBeginLoginResponseCbor, fromBoardCbor, fromBoardPageCbor, fromCategoryCbor, fromCategoryListCbor, fromCommentCbor, fromDomainListCbor, fromEmptyCbor, fromEndorsementCbor, fromEndorsementListCbor, fromFriendGroupCbor, fromFriendGroupListCbor, fromGithubMappingCbor, fromMappingListCbor, fromMentionGrantListCbor, fromNotificationPageCbor, fromPostCbor, fromPostPageCbor, fromRevisionListCbor, fromSubscriptionCbor, fromSubscriptionListCbor, fromThreadCbor, fromUnreadSummaryCbor, fromUserProfileCbor, fromUserSettingsCbor, toAddFriendRequestCbor, toBeginLoginRequestCbor, toCreateBoardRequestCbor, toCreateCategoryRequestCbor, toCreateCommentRequestCbor, toCreateFriendGroupRequestCbor, toCreateMappingRequestCbor, toCreatePostRequestCbor, toDeleteCategoryRequestCbor, toEditCommentRequestCbor, toEditPostRequestCbor, toEmptyCbor, toEndorseRequestCbor, toGetThreadRequestCbor, toListBoardsRequestCbor, toListNotificationsRequestCbor, toListPostsRequestCbor, toRemoveBoardMemberRequestCbor, toRemoveFriendRequestCbor, toSetBoardMemberRequestCbor, toSetMutedRequestCbor, toTargetRefCbor, toUpdateBoardRequestCbor, toUpdateCategoryRequestCbor, toUpdateSettingsRequestCbor } from "./codec.gen.ts";

export interface ServiceTransport {
  call(service: string, op: string, req: Uint8Array): Uint8Array;
}

export class AuthClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Start a login. The server signs a self-verifying nonce and returns
   * the identity-provider URL to open in the browser.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  beginLogin(req: BeginLoginRequest): BeginLoginResponse {
    const csilResp = this.t.call("AuthService", "begin-login", toBeginLoginRequestCbor(req));
    return fromBeginLoginResponseCbor(csilResp);
  }

  /**
   * Clear the caller's session cookie. Idempotent; never errors even if
   * already logged out.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  logout(req: Empty): Empty {
    const csilResp = this.t.call("AuthService", "logout", toEmptyCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * The caller's own profile, derived from their session cookie.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  whoami(req: Empty): UserProfile {
    const csilResp = this.t.call("AuthService", "whoami", toEmptyCbor(req));
    return fromUserProfileCbor(csilResp);
  }
}

export class BoardClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Cursor-paginated listing of all boards, ordered by title.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listBoards(req: ListBoardsRequest): BoardPage {
    const csilResp = this.t.call("BoardService", "list-boards", toListBoardsRequestCbor(req));
    return fromBoardPageCbor(csilResp);
  }

  /**
   * Look up one board by its slug.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  getBoard(req: BoardSlug): Board {
    const csilResp = this.t.call("BoardService", "get-board", encodeValue(req));
    return fromBoardCbor(csilResp);
  }

  /**
   * Admin-only: create a new board.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  createBoard(req: CreateBoardRequest): Board {
    const csilResp = this.t.call("BoardService", "create-board", toCreateBoardRequestCbor(req));
    return fromBoardCbor(csilResp);
  }

  /**
   * Admin-only: update a board's title/description.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  updateBoard(req: UpdateBoardRequest): Board {
    const csilResp = this.t.call("BoardService", "update-board", toUpdateBoardRequestCbor(req));
    return fromBoardCbor(csilResp);
  }

  /**
   * Admin-only: archive a board (read-only afterward, still browsable).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  archiveBoard(req: BoardID): Empty {
    const csilResp = this.t.call("BoardService", "archive-board", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Admin-only: assign or change a user's maintainer/moderator role on a
   * board.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  setBoardMember(req: SetBoardMemberRequest): Empty {
    const csilResp = this.t.call("BoardService", "set-board-member", toSetBoardMemberRequestCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Maintainer/moderator: remove a user's role on a board.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  removeBoardMember(req: RemoveBoardMemberRequest): Empty {
    const csilResp = this.t.call("BoardService", "remove-board-member", toRemoveBoardMemberRequestCbor(req));
    return fromEmptyCbor(csilResp);
  }
}

export class CategoryClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * List the categories that are available in one board.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listBoardCategories(req: BoardID): CategoryList {
    const csilResp = this.t.call("CategoryService", "list-board-categories", encodeValue(req));
    return fromCategoryListCbor(csilResp);
  }

  /**
   * Admin-only: create a category and attach it to one or more boards.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  createCategory(req: CreateCategoryRequest): Category {
    const csilResp = this.t.call("CategoryService", "create-category", toCreateCategoryRequestCbor(req));
    return fromCategoryCbor(csilResp);
  }

  /**
   * Admin-only: change category details, board assignments, or routing.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  updateCategory(req: UpdateCategoryRequest): Category {
    const csilResp = this.t.call("CategoryService", "update-category", toUpdateCategoryRequestCbor(req));
    return fromCategoryCbor(csilResp);
  }

  /**
   * Admin-only: remove a category. The caller must confirm removal from
   * all posts. Affected posts then use the virtual Uncategorized state.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  deleteCategory(req: DeleteCategoryRequest): Empty {
    const csilResp = this.t.call("CategoryService", "delete-category", toDeleteCategoryRequestCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * List all categories. The admin view uses this for categories that
   * are assigned only to archived boards.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listCategories(req: Empty): CategoryList {
    const csilResp = this.t.call("CategoryService", "list-categories", toEmptyCbor(req));
    return fromCategoryListCbor(csilResp);
  }
}

export class EndorsementClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Endorse a post or comment. Rejected if the caller already endorsed
   * it, if it's the caller's own content, or if the content is deleted.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  endorse(req: EndorseRequest): Endorsement {
    const csilResp = this.t.call("EndorsementService", "endorse", toEndorseRequestCbor(req));
    return fromEndorsementCbor(csilResp);
  }

  /**
   * Retract the caller's own endorsement.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  retract(req: EndorseRequest): Empty {
    const csilResp = this.t.call("EndorsementService", "retract", toEndorseRequestCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * The full endorser list for a target, pre-ordered per-viewer by the
   * server (friends first, then reputation).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listEndorsements(req: TargetRef): EndorsementList {
    const csilResp = this.t.call("EndorsementService", "list-endorsements", toTargetRefCbor(req));
    return fromEndorsementListCbor(csilResp);
  }
}

export class IntegrationClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Create a per-repo webhook mapping into a board.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  createGithubMapping(req: CreateMappingRequest): GithubMapping {
    const csilResp = this.t.call("IntegrationService", "create-github-mapping", toCreateMappingRequestCbor(req));
    return fromGithubMappingCbor(csilResp);
  }

  /**
   * All configured GitHub mappings.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listGithubMappings(req: Empty): MappingList {
    const csilResp = this.t.call("IntegrationService", "list-github-mappings", toEmptyCbor(req));
    return fromMappingListCbor(csilResp);
  }

  /**
   * Remove a GitHub mapping (stops ingestion for that repo; already
   * ingested content is unaffected).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  deleteGithubMapping(req: MappingID): Empty {
    const csilResp = this.t.call("IntegrationService", "delete-github-mapping", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Add a linkkeys domain to the trusted-domains registry.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  addTrustedDomain(req: Domain): Empty {
    const csilResp = this.t.call("IntegrationService", "add-trusted-domain", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Remove a linkkeys domain from the trusted-domains registry.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  removeTrustedDomain(req: Domain): Empty {
    const csilResp = this.t.call("IntegrationService", "remove-trusted-domain", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * All trusted domains.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listTrustedDomains(req: Empty): DomainList {
    const csilResp = this.t.call("IntegrationService", "list-trusted-domains", toEmptyCbor(req));
    return fromDomainListCbor(csilResp);
  }
}

export class NotificationClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Cursor-paginated notification inbox, newest first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listNotifications(req: ListNotificationsRequest): NotificationPage {
    const csilResp = this.t.call("NotificationService", "list-notifications", toListNotificationsRequestCbor(req));
    return fromNotificationPageCbor(csilResp);
  }

  /**
   * Mark a specific set of notifications read.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markNotificationRead(req: NotificationIDs): Empty {
    const csilResp = this.t.call("NotificationService", "mark-notification-read", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Mark every one of the caller's notifications read.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markAllRead(req: Empty): Empty {
    const csilResp = this.t.call("NotificationService", "mark-all-read", toEmptyCbor(req));
    return fromEmptyCbor(csilResp);
  }
}

export class ReadClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Mark an item (or a whole post) read: advances the watermark and/or
   * clears any unread override pinning it unread.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markRead(req: TargetRef): Empty {
    const csilResp = this.t.call("ReadService", "mark-read", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Pin an item unread regardless of the watermark, until it's
   * explicitly mark-read again.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  markUnread(req: TargetRef): Empty {
    const csilResp = this.t.call("ReadService", "mark-unread", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Per-board/post unread counts for the caller — the poll endpoint the
   * UI hits to drive unread badges.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  unreadSummary(req: Empty): UnreadSummary {
    const csilResp = this.t.call("ReadService", "unread-summary", toEmptyCbor(req));
    return fromUnreadSummaryCbor(csilResp);
  }
}

export class SettingsClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * The caller's own settings (defaults filled in).
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  getSettings(req: Empty): UserSettings {
    const csilResp = this.t.call("SettingsService", "get-settings", toEmptyCbor(req));
    return fromUserSettingsCbor(csilResp);
  }

  /**
   * Partial update — only fields present in the request are changed.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  updateSettings(req: UpdateSettingsRequest): UserSettings {
    const csilResp = this.t.call("SettingsService", "update-settings", toUpdateSettingsRequestCbor(req));
    return fromUserSettingsCbor(csilResp);
  }

  /**
   * Users the caller has granted permanent mention-notify permission to.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listMentionGrants(req: Empty): MentionGrantList {
    const csilResp = this.t.call("SettingsService", "list-mention-grants", toEmptyCbor(req));
    return fromMentionGrantListCbor(csilResp);
  }

  /**
   * Grant a user permanent mention-notify permission, independent of
   * shared subscriptions.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  grantMention(req: UserID): Empty {
    const csilResp = this.t.call("SettingsService", "grant-mention", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Revoke a previously granted mention-notify permission.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  revokeMention(req: UserID): Empty {
    const csilResp = this.t.call("SettingsService", "revoke-mention", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }
}

export class SocialClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * The caller's own friend groups and their membership.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listFriendGroups(req: Empty): FriendGroupList {
    const csilResp = this.t.call("SocialService", "list-friend-groups", toEmptyCbor(req));
    return fromFriendGroupListCbor(csilResp);
  }

  /**
   * Create a new (initially empty) friend group.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  createFriendGroup(req: CreateFriendGroupRequest): FriendGroup {
    const csilResp = this.t.call("SocialService", "create-friend-group", toCreateFriendGroupRequestCbor(req));
    return fromFriendGroupCbor(csilResp);
  }

  /**
   * Delete a friend group the caller owns, and its membership.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  deleteFriendGroup(req: GroupID): Empty {
    const csilResp = this.t.call("SocialService", "delete-friend-group", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Add a user to one of the caller's own friend groups.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  addFriend(req: AddFriendRequest): Empty {
    const csilResp = this.t.call("SocialService", "add-friend", toAddFriendRequestCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Remove a user from one of the caller's own friend groups.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  removeFriend(req: RemoveFriendRequest): Empty {
    const csilResp = this.t.call("SocialService", "remove-friend", toRemoveFriendRequestCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Resolve a handle to its user's public profile — lets the UI turn a
   * typed "@handle" into the UserID that grant-mention/add-friend
   * actually take, instead of making the caller paste a raw ULID.
   * Available to any authenticated user (a handle is public by
   * definition, unlike friend-group membership); not owner-scoped.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  resolveUser(req: Handle): UserProfile {
    const csilResp = this.t.call("SocialService", "resolve-user", encodeValue(req));
    return fromUserProfileCbor(csilResp);
  }
}

export class SubscriptionClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Subscribe to a board, post, or comment subtree.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  subscribe(req: TargetRef): Subscription {
    const csilResp = this.t.call("SubscriptionService", "subscribe", toTargetRefCbor(req));
    return fromSubscriptionCbor(csilResp);
  }

  /**
   * Remove a subscription entirely.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  unsubscribe(req: TargetRef): Empty {
    const csilResp = this.t.call("SubscriptionService", "unsubscribe", toTargetRefCbor(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Toggle mute on an existing subscription without removing it.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  setMuted(req: SetMutedRequest): Subscription {
    const csilResp = this.t.call("SubscriptionService", "set-muted", toSetMutedRequestCbor(req));
    return fromSubscriptionCbor(csilResp);
  }

  /**
   * All of the caller's subscriptions.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listSubscriptions(req: Empty): SubscriptionList {
    const csilResp = this.t.call("SubscriptionService", "list-subscriptions", toEmptyCbor(req));
    return fromSubscriptionListCbor(csilResp);
  }
}

export class ThreadClient {
  constructor(private readonly t: ServiceTransport) {}

  /**
   * Cursor-paginated listing of a board's posts, newest activity first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listPosts(req: ListPostsRequest): PostPage {
    const csilResp = this.t.call("ThreadService", "list-posts", toListPostsRequestCbor(req));
    return fromPostPageCbor(csilResp);
  }

  /**
   * The full post plus its whole comment tree, depth-first ordered.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  getThread(req: GetThreadRequest): Thread {
    const csilResp = this.t.call("ThreadService", "get-thread", toGetThreadRequestCbor(req));
    return fromThreadCbor(csilResp);
  }

  /**
   * Start a new thread on a board.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  createPost(req: CreatePostRequest): Post {
    const csilResp = this.t.call("ThreadService", "create-post", toCreatePostRequestCbor(req));
    return fromPostCbor(csilResp);
  }

  /**
   * Reply to a post, optionally nested under an existing comment.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  createComment(req: CreateCommentRequest): Comment {
    const csilResp = this.t.call("ThreadService", "create-comment", toCreateCommentRequestCbor(req));
    return fromCommentCbor(csilResp);
  }

  /**
   * Edit a post's title/body; snapshots the prior state as a revision in
   * the same transaction.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  editPost(req: EditPostRequest): Post {
    const csilResp = this.t.call("ThreadService", "edit-post", toEditPostRequestCbor(req));
    return fromPostCbor(csilResp);
  }

  /**
   * Edit a comment's body; snapshots the prior state as a revision.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  editComment(req: EditCommentRequest): Comment {
    const csilResp = this.t.call("ThreadService", "edit-comment", toEditCommentRequestCbor(req));
    return fromCommentCbor(csilResp);
  }

  /**
   * Full edit history for a post or comment, newest first.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  listRevisions(req: TargetRef): RevisionList {
    const csilResp = this.t.call("ThreadService", "list-revisions", toTargetRefCbor(req));
    return fromRevisionListCbor(csilResp);
  }

  /**
   * Soft-delete a post (author or moderator/maintainer). The post
   * becomes a tombstone; replies remain.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  deletePost(req: PostID): Empty {
    const csilResp = this.t.call("ThreadService", "delete-post", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }

  /**
   * Soft-delete a comment (author or moderator/maintainer). The comment
   * becomes a tombstone; its replies remain.
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  deleteComment(req: CommentID): Empty {
    const csilResp = this.t.call("ThreadService", "delete-comment", encodeValue(req));
    return fromEmptyCbor(csilResp);
  }
}

export class ApiClient {
  readonly auth: AuthClient;
  readonly board: BoardClient;
  readonly category: CategoryClient;
  readonly endorsement: EndorsementClient;
  readonly integration: IntegrationClient;
  readonly notification: NotificationClient;
  readonly read: ReadClient;
  readonly settings: SettingsClient;
  readonly social: SocialClient;
  readonly subscription: SubscriptionClient;
  readonly thread: ThreadClient;
  constructor(t: ServiceTransport) {
    this.auth = new AuthClient(t);
    this.board = new BoardClient(t);
    this.category = new CategoryClient(t);
    this.endorsement = new EndorsementClient(t);
    this.integration = new IntegrationClient(t);
    this.notification = new NotificationClient(t);
    this.read = new ReadClient(t);
    this.settings = new SettingsClient(t);
    this.social = new SocialClient(t);
    this.subscription = new SubscriptionClient(t);
    this.thread = new ThreadClient(t);
  }
}
