// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-codec

import type { AddFriendRequest, AuthError, BeginLoginRequest, BeginLoginResponse, Board, BoardID, BoardKind, BoardPage, BoardRole, BoardUnread, Comment, CommentID, CreateBoardRequest, CreateCommentRequest, CreateFriendGroupRequest, CreateMappingRequest, CreatePostRequest, DomainEntry, DomainList, EditCommentRequest, EditPostRequest, Empty, EndorseRequest, Endorsement, EndorsementID, EndorsementList, FirepitError, FriendGroup, FriendGroupList, GetThreadRequest, GithubMapping, GroupID, ListBoardsRequest, ListNotificationsRequest, ListPostsRequest, MappingID, MappingList, MentionGrant, MentionGrantList, MentionPolicy, NotFoundError, Notification, NotificationEvent, NotificationID, NotificationPage, OriginKind, PageCursor, Post, PostID, PostPage, RemoveBoardMemberRequest, RemoveFriendRequest, Revision, RevisionID, RevisionList, SetBoardMemberRequest, SetMutedRequest, Subscription, SubscriptionID, SubscriptionList, TargetRef, TargetType, Thread, ThreadMode, UnreadSummary, UpdateBoardRequest, UpdateSettingsRequest, UserID, UserKind, UserProfile, UserSettings } from "./types.gen";

/** A CBOR semantic tag wrapping an inner value (e.g. tag 0 timestamp, tag 4 decimal). */
export type CborTag = { readonly tag: number; readonly value: CborValue };

/** A minimal canonical-CBOR value tree: a closed set of node variants. */
export type CborValue =
  | number
  | bigint
  | boolean
  | null
  | string
  | Uint8Array
  | CborValue[]
  | Map<CborValue, CborValue>
  | CborTag;

const csilTextEncoder = new TextEncoder();
const csilTextDecoder = new TextDecoder();

function head(major: number, n: number | bigint, out: number[]): void {
  const mt = major << 5;
  const big = typeof n === "bigint" ? n : BigInt(n);
  if (big < 24n) {
    out.push(mt | Number(big));
  } else if (big < 0x100n) {
    out.push(mt | 24, Number(big) & 0xff);
  } else if (big < 0x10000n) {
    out.push(mt | 25, Number((big >> 8n) & 0xffn), Number(big & 0xffn));
  } else if (big < 0x100000000n) {
    out.push(mt | 26);
    for (let s = 24n; s >= 0n; s -= 8n) out.push(Number((big >> s) & 0xffn));
  } else {
    out.push(mt | 27);
    for (let s = 56n; s >= 0n; s -= 8n) out.push(Number((big >> s) & 0xffn));
  }
}

function encInt(n: bigint, out: number[]): void {
  if (n >= 0n) head(0, n, out);
  else head(1, -1n - n, out);
}

function encFloat(d: number, out: number[]): void {
  out.push(0xfb);
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, d, false);
  for (let i = 0; i < 8; i++) out.push(view.getUint8(i));
}

function encInto(v: CborValue, out: number[]): void {
  if (typeof v === "number") {
    if (Number.isInteger(v)) encInt(BigInt(v), out);
    else encFloat(v, out);
  } else if (typeof v === "bigint") {
    encInt(v, out);
  } else if (typeof v === "boolean") {
    out.push(v ? 0xf5 : 0xf4);
  } else if (v === null) {
    out.push(0xf6);
  } else if (typeof v === "string") {
    const bytes = csilTextEncoder.encode(v);
    head(3, bytes.length, out);
    for (const b of bytes) out.push(b);
  } else if (v instanceof Uint8Array) {
    head(2, v.length, out);
    for (const b of v) out.push(b);
  } else if (Array.isArray(v)) {
    head(4, v.length, out);
    for (const x of v) encInto(x, out);
  } else if (v instanceof Map) {
    head(5, v.size, out);
    for (const [k, val] of v) {
      encInto(k, out);
      encInto(val, out);
    }
  } else {
    head(6, v.tag, out);
    encInto(v.value, out);
  }
}

/** Encode a CBOR value tree to canonical CSIL CBOR bytes. */
export function encodeValue(value: CborValue): Uint8Array {
  const out: number[] = [];
  encInto(value, out);
  return Uint8Array.from(out);
}

type Cursor = { b: Uint8Array; pos: number };

function readArg(st: Cursor, low: number): bigint {
  if (low < 24) {
    st.pos += 1;
    return BigInt(low);
  }
  if (low === 24) {
    const v = BigInt(st.b[st.pos + 1]);
    st.pos += 2;
    return v;
  }
  if (low === 25) {
    let v = 0n;
    for (let i = 1; i <= 2; i++) v = (v << 8n) | BigInt(st.b[st.pos + i]);
    st.pos += 3;
    return v;
  }
  if (low === 26) {
    let v = 0n;
    for (let i = 1; i <= 4; i++) v = (v << 8n) | BigInt(st.b[st.pos + i]);
    st.pos += 5;
    return v;
  }
  if (low === 27) {
    let v = 0n;
    for (let i = 1; i <= 8; i++) v = (v << 8n) | BigInt(st.b[st.pos + i]);
    st.pos += 9;
    return v;
  }
  throw new Error("malformed CBOR argument");
}

function smallInt(arg: bigint): number | bigint {
  return arg <= BigInt(Number.MAX_SAFE_INTEGER) ? Number(arg) : arg;
}

function readFloat(st: Cursor, low: number): number {
  const bits = readArg(st, low);
  if (low === 26) {
    const view = new DataView(new ArrayBuffer(4));
    view.setUint32(0, Number(bits), false);
    return view.getFloat32(0, false);
  }
  const view = new DataView(new ArrayBuffer(8));
  view.setBigUint64(0, bits, false);
  return view.getFloat64(0, false);
}

function decInto(st: Cursor): CborValue {
  const ib = st.b[st.pos];
  const major = ib >> 5;
  const low = ib & 0x1f;
  if (major === 7) {
    if (low === 20) {
      st.pos += 1;
      return false;
    }
    if (low === 21) {
      st.pos += 1;
      return true;
    }
    if (low === 22 || low === 23) {
      st.pos += 1;
      return null;
    }
    if (low === 26 || low === 27) return readFloat(st, low);
    throw new Error("malformed CBOR simple value");
  }
  const arg = readArg(st, low);
  switch (major) {
    case 0:
      return smallInt(arg);
    case 1: {
      const n = -1n - arg;
      return n >= BigInt(Number.MIN_SAFE_INTEGER) ? Number(n) : n;
    }
    case 2: {
      const n = Number(arg);
      const slice = st.b.slice(st.pos, st.pos + n);
      st.pos += n;
      return slice;
    }
    case 3: {
      const n = Number(arg);
      const text = csilTextDecoder.decode(st.b.subarray(st.pos, st.pos + n));
      st.pos += n;
      return text;
    }
    case 4: {
      const n = Number(arg);
      const arr: CborValue[] = [];
      for (let i = 0; i < n; i++) arr.push(decInto(st));
      return arr;
    }
    case 5: {
      const n = Number(arg);
      const m = new Map<CborValue, CborValue>();
      for (let i = 0; i < n; i++) {
        const k = decInto(st);
        const val = decInto(st);
        m.set(k, val);
      }
      return m;
    }
    case 6: {
      const inner = decInto(st);
      return { tag: Number(arg), value: inner };
    }
    default:
      throw new Error("malformed CBOR major type");
  }
}

/** Decode a CSIL CBOR byte payload into a CBOR value tree. */
export function decode(bytes: Uint8Array): CborValue {
  const st: Cursor = { b: bytes, pos: 0 };
  const v = decInto(st);
  if (st.pos !== bytes.length) throw new Error("trailing bytes after CBOR value");
  return v;
}

/** The value for `key` in a CBOR map node, or `undefined` when absent. */
export function mapGet(value: CborValue, key: string): CborValue | undefined {
  return value instanceof Map ? value.get(key) : undefined;
}

/** The value for a required `key`; throws when the field is missing. */
export function requireKey(value: CborValue, key: string): CborValue {
  const v = mapGet(value, key);
  if (v === undefined) throw new Error(`missing required field: ${key}`);
  return v;
}

export function asNumber(value: CborValue): number {
  if (typeof value === "number") return value;
  if (typeof value === "bigint") return Number(value);
  throw new Error("expected a number");
}

export function asString(value: CborValue): string {
  if (typeof value === "string") return value;
  throw new Error("expected a text string");
}

export function asBytes(value: CborValue): Uint8Array {
  if (value instanceof Uint8Array) return value;
  throw new Error("expected a byte string");
}

export function asBool(value: CborValue): boolean {
  if (typeof value === "boolean") return value;
  throw new Error("expected a boolean");
}

export function asArray(value: CborValue): CborValue[] {
  if (Array.isArray(value)) return value;
  throw new Error("expected an array");
}

export function asMap(value: CborValue): Map<CborValue, CborValue> {
  if (value instanceof Map) return value;
  throw new Error("expected a map");
}

function asTagged(value: CborValue, tag: number): CborValue {
  if (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !(value instanceof Uint8Array) &&
    !(value instanceof Map) &&
    value.tag === tag
  ) {
    return value.value;
  }
  throw new Error(`expected tag ${tag}`);
}

/** Decode a tag-0 (RFC 3339, UTC) timestamp into a `Date`. */
export function asTimestamp(value: CborValue): Date {
  return new Date(asString(asTagged(value, 0)));
}

/** Decode a tag-4 decimal fraction into its `[exponent, mantissa]` payload. */
export function asDecimalPayload(value: CborValue): [number | bigint, number | bigint] {
  const arr = asArray(asTagged(value, 4));
  const intOf = (x: CborValue): number | bigint => {
    if (typeof x === "number" || typeof x === "bigint") return x;
    throw new Error("expected an integer in decimal payload");
  };
  return [intOf(arr[0]), intOf(arr[1])];
}

/** A `Date` rendered as the canonical tag-0 text: RFC 3339, UTC, `Z` offset. */
export function csilTsToText(d: Date): string {
  return d.toISOString().replace(/\.000Z$/, "Z");
}

export function toTargetRefCborValue(v: TargetRef): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("target_id", v.targetId);
  csilMap.set("target_type", v.targetType);
  return csilMap;
}

export function fromTargetRefCborValue(value: CborValue): TargetRef {
  return {
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
  };
}

export function toTargetRefCbor(v: TargetRef): Uint8Array {
  return encodeValue(toTargetRefCborValue(v));
}

export function fromTargetRefCbor(bytes: Uint8Array): TargetRef {
  return fromTargetRefCborValue(decode(bytes));
}

export function toEmptyCborValue(v: Empty): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  return csilMap;
}

export function fromEmptyCborValue(value: CborValue): Empty {
  void value;
  return {} as Empty;
}

export function toEmptyCbor(v: Empty): Uint8Array {
  return encodeValue(toEmptyCborValue(v));
}

export function fromEmptyCbor(bytes: Uint8Array): Empty {
  return fromEmptyCborValue(decode(bytes));
}

export function toFirepitErrorCborValue(v: FirepitError): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("code", v.code);
  if (v.field !== undefined) csilMap.set("field", v.field);
  csilMap.set("message", v.message);
  return csilMap;
}

export function fromFirepitErrorCborValue(value: CborValue): FirepitError {
  return {
    code: asNumber(requireKey(value, "code")),
    message: asString(requireKey(value, "message")),
    field: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "field")),
  };
}

export function toFirepitErrorCbor(v: FirepitError): Uint8Array {
  return encodeValue(toFirepitErrorCborValue(v));
}

export function fromFirepitErrorCbor(bytes: Uint8Array): FirepitError {
  return fromFirepitErrorCborValue(decode(bytes));
}

export function toAuthErrorCborValue(v: AuthError): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("code", v.code);
  csilMap.set("message", v.message);
  return csilMap;
}

export function fromAuthErrorCborValue(value: CborValue): AuthError {
  return {
    code: asNumber(requireKey(value, "code")),
    message: asString(requireKey(value, "message")),
  };
}

export function toAuthErrorCbor(v: AuthError): Uint8Array {
  return encodeValue(toAuthErrorCborValue(v));
}

export function fromAuthErrorCbor(bytes: Uint8Array): AuthError {
  return fromAuthErrorCborValue(decode(bytes));
}

export function toNotFoundErrorCborValue(v: NotFoundError): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("code", v.code);
  csilMap.set("message", v.message);
  csilMap.set("resource_type", v.resourceType);
  return csilMap;
}

export function fromNotFoundErrorCborValue(value: CborValue): NotFoundError {
  return {
    code: asNumber(requireKey(value, "code")),
    message: asString(requireKey(value, "message")),
    resourceType: asString(requireKey(value, "resource_type")),
  };
}

export function toNotFoundErrorCbor(v: NotFoundError): Uint8Array {
  return encodeValue(toNotFoundErrorCborValue(v));
}

export function fromNotFoundErrorCbor(bytes: Uint8Array): NotFoundError {
  return fromNotFoundErrorCborValue(decode(bytes));
}

export function toBeginLoginRequestCborValue(v: BeginLoginRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("domain", v.domain);
  return csilMap;
}

export function fromBeginLoginRequestCborValue(value: CborValue): BeginLoginRequest {
  return {
    domain: asString(requireKey(value, "domain")),
  };
}

export function toBeginLoginRequestCbor(v: BeginLoginRequest): Uint8Array {
  return encodeValue(toBeginLoginRequestCborValue(v));
}

export function fromBeginLoginRequestCbor(bytes: Uint8Array): BeginLoginRequest {
  return fromBeginLoginRequestCborValue(decode(bytes));
}

export function toBeginLoginResponseCborValue(v: BeginLoginResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("redirect_url", v.redirectUrl);
  return csilMap;
}

export function fromBeginLoginResponseCborValue(value: CborValue): BeginLoginResponse {
  return {
    redirectUrl: asString(requireKey(value, "redirect_url")),
  };
}

export function toBeginLoginResponseCbor(v: BeginLoginResponse): Uint8Array {
  return encodeValue(toBeginLoginResponseCborValue(v));
}

export function fromBeginLoginResponseCbor(bytes: Uint8Array): BeginLoginResponse {
  return fromBeginLoginResponseCborValue(decode(bytes));
}

export function toUserProfileCborValue(v: UserProfile): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("kind", v.kind);
  csilMap.set("roles", v.roles);
  csilMap.set("handle", v.handle);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  csilMap.set("display_name", v.displayName);
  csilMap.set("linkkeys_domain", v.linkkeysDomain);
  return csilMap;
}

export function fromUserProfileCborValue(value: CborValue): UserProfile {
  return {
    id: asString(requireKey(value, "id")),
    linkkeysDomain: asString(requireKey(value, "linkkeys_domain")),
    handle: asString(requireKey(value, "handle")),
    displayName: asString(requireKey(value, "display_name")),
    kind: (requireKey(value, "kind") as unknown as UserKind),
    roles: asArray(requireKey(value, "roles")).map((csilE) => asString(csilE)),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toUserProfileCbor(v: UserProfile): Uint8Array {
  return encodeValue(toUserProfileCborValue(v));
}

export function fromUserProfileCbor(bytes: Uint8Array): UserProfile {
  return fromUserProfileCborValue(decode(bytes));
}

export function toBoardCborValue(v: Board): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("kind", v.kind);
  csilMap.set("slug", v.slug);
  csilMap.set("title", v.title);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  csilMap.set("created_by", v.createdBy);
  if (v.archivedAt !== undefined) csilMap.set("archived_at", { tag: 0, value: csilTsToText(v.archivedAt) });
  if (v.description !== undefined) csilMap.set("description", v.description);
  return csilMap;
}

export function fromBoardCborValue(value: CborValue): Board {
  return {
    id: asString(requireKey(value, "id")),
    slug: asString(requireKey(value, "slug")),
    title: asString(requireKey(value, "title")),
    description: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "description")),
    kind: (requireKey(value, "kind") as unknown as BoardKind),
    createdBy: asString(requireKey(value, "created_by")),
    archivedAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "archived_at")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toBoardCbor(v: Board): Uint8Array {
  return encodeValue(toBoardCborValue(v));
}

export function fromBoardCbor(bytes: Uint8Array): Board {
  return fromBoardCborValue(decode(bytes));
}

export function toListBoardsRequestCborValue(v: ListBoardsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.limit !== undefined) csilMap.set("limit", v.limit);
  if (v.cursor !== undefined) csilMap.set("cursor", v.cursor);
  return csilMap;
}

export function fromListBoardsRequestCborValue(value: CborValue): ListBoardsRequest {
  return {
    cursor: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "cursor")),
    limit: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asNumber(csilV))(mapGet(value, "limit")),
  };
}

export function toListBoardsRequestCbor(v: ListBoardsRequest): Uint8Array {
  return encodeValue(toListBoardsRequestCborValue(v));
}

export function fromListBoardsRequestCbor(bytes: Uint8Array): ListBoardsRequest {
  return fromListBoardsRequestCborValue(decode(bytes));
}

export function toBoardPageCborValue(v: BoardPage): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("boards", v.boards.map((csilE): CborValue => toBoardCborValue(csilE)));
  if (v.nextCursor !== undefined) csilMap.set("next_cursor", v.nextCursor);
  return csilMap;
}

export function fromBoardPageCborValue(value: CborValue): BoardPage {
  return {
    boards: asArray(requireKey(value, "boards")).map((csilE) => fromBoardCborValue(csilE)),
    nextCursor: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "next_cursor")),
  };
}

export function toBoardPageCbor(v: BoardPage): Uint8Array {
  return encodeValue(toBoardPageCborValue(v));
}

export function fromBoardPageCbor(bytes: Uint8Array): BoardPage {
  return fromBoardPageCborValue(decode(bytes));
}

export function toCreateBoardRequestCborValue(v: CreateBoardRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("kind", v.kind);
  csilMap.set("slug", v.slug);
  csilMap.set("title", v.title);
  if (v.description !== undefined) csilMap.set("description", v.description);
  return csilMap;
}

export function fromCreateBoardRequestCborValue(value: CborValue): CreateBoardRequest {
  return {
    slug: asString(requireKey(value, "slug")),
    title: asString(requireKey(value, "title")),
    description: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "description")),
    kind: (requireKey(value, "kind") as unknown as BoardKind),
  };
}

export function toCreateBoardRequestCbor(v: CreateBoardRequest): Uint8Array {
  return encodeValue(toCreateBoardRequestCborValue(v));
}

export function fromCreateBoardRequestCbor(bytes: Uint8Array): CreateBoardRequest {
  return fromCreateBoardRequestCborValue(decode(bytes));
}

export function toUpdateBoardRequestCborValue(v: UpdateBoardRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  if (v.title !== undefined) csilMap.set("title", v.title);
  if (v.description !== undefined) csilMap.set("description", v.description);
  return csilMap;
}

export function fromUpdateBoardRequestCborValue(value: CborValue): UpdateBoardRequest {
  return {
    id: asString(requireKey(value, "id")),
    title: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "title")),
    description: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "description")),
  };
}

export function toUpdateBoardRequestCbor(v: UpdateBoardRequest): Uint8Array {
  return encodeValue(toUpdateBoardRequestCborValue(v));
}

export function fromUpdateBoardRequestCbor(bytes: Uint8Array): UpdateBoardRequest {
  return fromUpdateBoardRequestCborValue(decode(bytes));
}

export function toSetBoardMemberRequestCborValue(v: SetBoardMemberRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("role", v.role);
  csilMap.set("user_id", v.userId);
  csilMap.set("board_id", v.boardId);
  return csilMap;
}

export function fromSetBoardMemberRequestCborValue(value: CborValue): SetBoardMemberRequest {
  return {
    boardId: asString(requireKey(value, "board_id")),
    userId: asString(requireKey(value, "user_id")),
    role: (requireKey(value, "role") as unknown as BoardRole),
  };
}

export function toSetBoardMemberRequestCbor(v: SetBoardMemberRequest): Uint8Array {
  return encodeValue(toSetBoardMemberRequestCborValue(v));
}

export function fromSetBoardMemberRequestCbor(bytes: Uint8Array): SetBoardMemberRequest {
  return fromSetBoardMemberRequestCborValue(decode(bytes));
}

export function toRemoveBoardMemberRequestCborValue(v: RemoveBoardMemberRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("user_id", v.userId);
  csilMap.set("board_id", v.boardId);
  return csilMap;
}

export function fromRemoveBoardMemberRequestCborValue(value: CborValue): RemoveBoardMemberRequest {
  return {
    boardId: asString(requireKey(value, "board_id")),
    userId: asString(requireKey(value, "user_id")),
  };
}

export function toRemoveBoardMemberRequestCbor(v: RemoveBoardMemberRequest): Uint8Array {
  return encodeValue(toRemoveBoardMemberRequestCborValue(v));
}

export function fromRemoveBoardMemberRequestCbor(bytes: Uint8Array): RemoveBoardMemberRequest {
  return fromRemoveBoardMemberRequestCborValue(decode(bytes));
}

export function toPostCborValue(v: Post): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("title", v.title);
  csilMap.set("origin", v.origin);
  csilMap.set("body_md", v.bodyMd);
  csilMap.set("board_id", v.boardId);
  csilMap.set("author_id", v.authorId);
  if (v.editedAt !== undefined) csilMap.set("edited_at", { tag: 0, value: csilTsToText(v.editedAt) });
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  if (v.deletedAt !== undefined) csilMap.set("deleted_at", { tag: 0, value: csilTsToText(v.deletedAt) });
  if (v.originRef !== undefined) csilMap.set("origin_ref", v.originRef);
  csilMap.set("comment_count", v.commentCount);
  csilMap.set("last_activity_at", { tag: 0, value: csilTsToText(v.lastActivityAt) });
  return csilMap;
}

export function fromPostCborValue(value: CborValue): Post {
  return {
    id: asString(requireKey(value, "id")),
    boardId: asString(requireKey(value, "board_id")),
    authorId: asString(requireKey(value, "author_id")),
    title: asString(requireKey(value, "title")),
    bodyMd: asString(requireKey(value, "body_md")),
    origin: (requireKey(value, "origin") as unknown as OriginKind),
    originRef: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "origin_ref")),
    commentCount: asNumber(requireKey(value, "comment_count")),
    lastActivityAt: asTimestamp(requireKey(value, "last_activity_at")),
    editedAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "edited_at")),
    deletedAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "deleted_at")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toPostCbor(v: Post): Uint8Array {
  return encodeValue(toPostCborValue(v));
}

export function fromPostCbor(bytes: Uint8Array): Post {
  return fromPostCborValue(decode(bytes));
}

export function toCommentCborValue(v: Comment): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("origin", v.origin);
  csilMap.set("body_md", v.bodyMd);
  csilMap.set("post_id", v.postId);
  csilMap.set("author_id", v.authorId);
  if (v.editedAt !== undefined) csilMap.set("edited_at", { tag: 0, value: csilTsToText(v.editedAt) });
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  if (v.deletedAt !== undefined) csilMap.set("deleted_at", { tag: 0, value: csilTsToText(v.deletedAt) });
  if (v.originRef !== undefined) csilMap.set("origin_ref", v.originRef);
  if (v.parentCommentId !== undefined) csilMap.set("parent_comment_id", v.parentCommentId);
  return csilMap;
}

export function fromCommentCborValue(value: CborValue): Comment {
  return {
    id: asString(requireKey(value, "id")),
    postId: asString(requireKey(value, "post_id")),
    parentCommentId: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "parent_comment_id")),
    authorId: asString(requireKey(value, "author_id")),
    bodyMd: asString(requireKey(value, "body_md")),
    origin: (requireKey(value, "origin") as unknown as OriginKind),
    originRef: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "origin_ref")),
    editedAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "edited_at")),
    deletedAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "deleted_at")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toCommentCbor(v: Comment): Uint8Array {
  return encodeValue(toCommentCborValue(v));
}

export function fromCommentCbor(bytes: Uint8Array): Comment {
  return fromCommentCborValue(decode(bytes));
}

export function toListPostsRequestCborValue(v: ListPostsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.limit !== undefined) csilMap.set("limit", v.limit);
  if (v.cursor !== undefined) csilMap.set("cursor", v.cursor);
  csilMap.set("board_id", v.boardId);
  return csilMap;
}

export function fromListPostsRequestCborValue(value: CborValue): ListPostsRequest {
  return {
    boardId: asString(requireKey(value, "board_id")),
    cursor: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "cursor")),
    limit: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asNumber(csilV))(mapGet(value, "limit")),
  };
}

export function toListPostsRequestCbor(v: ListPostsRequest): Uint8Array {
  return encodeValue(toListPostsRequestCborValue(v));
}

export function fromListPostsRequestCbor(bytes: Uint8Array): ListPostsRequest {
  return fromListPostsRequestCborValue(decode(bytes));
}

export function toPostPageCborValue(v: PostPage): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("posts", v.posts.map((csilE): CborValue => toPostCborValue(csilE)));
  if (v.nextCursor !== undefined) csilMap.set("next_cursor", v.nextCursor);
  return csilMap;
}

export function fromPostPageCborValue(value: CborValue): PostPage {
  return {
    posts: asArray(requireKey(value, "posts")).map((csilE) => fromPostCborValue(csilE)),
    nextCursor: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "next_cursor")),
  };
}

export function toPostPageCbor(v: PostPage): Uint8Array {
  return encodeValue(toPostPageCborValue(v));
}

export function fromPostPageCbor(bytes: Uint8Array): PostPage {
  return fromPostPageCborValue(decode(bytes));
}

export function toGetThreadRequestCborValue(v: GetThreadRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("post_id", v.postId);
  return csilMap;
}

export function fromGetThreadRequestCborValue(value: CborValue): GetThreadRequest {
  return {
    postId: asString(requireKey(value, "post_id")),
  };
}

export function toGetThreadRequestCbor(v: GetThreadRequest): Uint8Array {
  return encodeValue(toGetThreadRequestCborValue(v));
}

export function fromGetThreadRequestCbor(bytes: Uint8Array): GetThreadRequest {
  return fromGetThreadRequestCborValue(decode(bytes));
}

export function toThreadCborValue(v: Thread): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("post", toPostCborValue(v.post));
  csilMap.set("comments", v.comments.map((csilE): CborValue => toCommentCborValue(csilE)));
  return csilMap;
}

export function fromThreadCborValue(value: CborValue): Thread {
  return {
    post: fromPostCborValue(requireKey(value, "post")),
    comments: asArray(requireKey(value, "comments")).map((csilE) => fromCommentCborValue(csilE)),
  };
}

export function toThreadCbor(v: Thread): Uint8Array {
  return encodeValue(toThreadCborValue(v));
}

export function fromThreadCbor(bytes: Uint8Array): Thread {
  return fromThreadCborValue(decode(bytes));
}

export function toCreatePostRequestCborValue(v: CreatePostRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("title", v.title);
  csilMap.set("body_md", v.bodyMd);
  csilMap.set("board_id", v.boardId);
  return csilMap;
}

export function fromCreatePostRequestCborValue(value: CborValue): CreatePostRequest {
  return {
    boardId: asString(requireKey(value, "board_id")),
    title: asString(requireKey(value, "title")),
    bodyMd: asString(requireKey(value, "body_md")),
  };
}

export function toCreatePostRequestCbor(v: CreatePostRequest): Uint8Array {
  return encodeValue(toCreatePostRequestCborValue(v));
}

export function fromCreatePostRequestCbor(bytes: Uint8Array): CreatePostRequest {
  return fromCreatePostRequestCborValue(decode(bytes));
}

export function toCreateCommentRequestCborValue(v: CreateCommentRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("body_md", v.bodyMd);
  csilMap.set("post_id", v.postId);
  if (v.parentCommentId !== undefined) csilMap.set("parent_comment_id", v.parentCommentId);
  return csilMap;
}

export function fromCreateCommentRequestCborValue(value: CborValue): CreateCommentRequest {
  return {
    postId: asString(requireKey(value, "post_id")),
    parentCommentId: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "parent_comment_id")),
    bodyMd: asString(requireKey(value, "body_md")),
  };
}

export function toCreateCommentRequestCbor(v: CreateCommentRequest): Uint8Array {
  return encodeValue(toCreateCommentRequestCborValue(v));
}

export function fromCreateCommentRequestCbor(bytes: Uint8Array): CreateCommentRequest {
  return fromCreateCommentRequestCborValue(decode(bytes));
}

export function toEditPostRequestCborValue(v: EditPostRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("title", v.title);
  csilMap.set("body_md", v.bodyMd);
  return csilMap;
}

export function fromEditPostRequestCborValue(value: CborValue): EditPostRequest {
  return {
    id: asString(requireKey(value, "id")),
    title: asString(requireKey(value, "title")),
    bodyMd: asString(requireKey(value, "body_md")),
  };
}

export function toEditPostRequestCbor(v: EditPostRequest): Uint8Array {
  return encodeValue(toEditPostRequestCborValue(v));
}

export function fromEditPostRequestCbor(bytes: Uint8Array): EditPostRequest {
  return fromEditPostRequestCborValue(decode(bytes));
}

export function toEditCommentRequestCborValue(v: EditCommentRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("body_md", v.bodyMd);
  return csilMap;
}

export function fromEditCommentRequestCborValue(value: CborValue): EditCommentRequest {
  return {
    id: asString(requireKey(value, "id")),
    bodyMd: asString(requireKey(value, "body_md")),
  };
}

export function toEditCommentRequestCbor(v: EditCommentRequest): Uint8Array {
  return encodeValue(toEditCommentRequestCborValue(v));
}

export function fromEditCommentRequestCbor(bytes: Uint8Array): EditCommentRequest {
  return fromEditCommentRequestCborValue(decode(bytes));
}

export function toRevisionCborValue(v: Revision): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("editor_id", v.editorId);
  csilMap.set("target_id", v.targetId);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  if (v.prevTitle !== undefined) csilMap.set("prev_title", v.prevTitle);
  csilMap.set("target_type", v.targetType);
  csilMap.set("prev_body_md", v.prevBodyMd);
  return csilMap;
}

export function fromRevisionCborValue(value: CborValue): Revision {
  return {
    id: asString(requireKey(value, "id")),
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
    editorId: asString(requireKey(value, "editor_id")),
    prevTitle: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "prev_title")),
    prevBodyMd: asString(requireKey(value, "prev_body_md")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toRevisionCbor(v: Revision): Uint8Array {
  return encodeValue(toRevisionCborValue(v));
}

export function fromRevisionCbor(bytes: Uint8Array): Revision {
  return fromRevisionCborValue(decode(bytes));
}

export function toRevisionListCborValue(v: RevisionList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("revisions", v.revisions.map((csilE): CborValue => toRevisionCborValue(csilE)));
  return csilMap;
}

export function fromRevisionListCborValue(value: CborValue): RevisionList {
  return {
    revisions: asArray(requireKey(value, "revisions")).map((csilE) => fromRevisionCborValue(csilE)),
  };
}

export function toRevisionListCbor(v: RevisionList): Uint8Array {
  return encodeValue(toRevisionListCborValue(v));
}

export function fromRevisionListCbor(bytes: Uint8Array): RevisionList {
  return fromRevisionListCborValue(decode(bytes));
}

export function toEndorseRequestCborValue(v: EndorseRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("target_id", v.targetId);
  csilMap.set("target_type", v.targetType);
  return csilMap;
}

export function fromEndorseRequestCborValue(value: CborValue): EndorseRequest {
  return {
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
  };
}

export function toEndorseRequestCbor(v: EndorseRequest): Uint8Array {
  return encodeValue(toEndorseRequestCborValue(v));
}

export function fromEndorseRequestCbor(bytes: Uint8Array): EndorseRequest {
  return fromEndorseRequestCborValue(decode(bytes));
}

export function toEndorsementCborValue(v: Endorsement): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("user_id", v.userId);
  csilMap.set("target_id", v.targetId);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  if (v.roleBadge !== undefined) csilMap.set("role_badge", v.roleBadge);
  csilMap.set("target_type", v.targetType);
  return csilMap;
}

export function fromEndorsementCborValue(value: CborValue): Endorsement {
  return {
    id: asString(requireKey(value, "id")),
    userId: asString(requireKey(value, "user_id")),
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
    roleBadge: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "role_badge")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toEndorsementCbor(v: Endorsement): Uint8Array {
  return encodeValue(toEndorsementCborValue(v));
}

export function fromEndorsementCbor(bytes: Uint8Array): Endorsement {
  return fromEndorsementCborValue(decode(bytes));
}

export function toEndorsementListCborValue(v: EndorsementList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("endorsements", v.endorsements.map((csilE): CborValue => toEndorsementCborValue(csilE)));
  return csilMap;
}

export function fromEndorsementListCborValue(value: CborValue): EndorsementList {
  return {
    endorsements: asArray(requireKey(value, "endorsements")).map((csilE) => fromEndorsementCborValue(csilE)),
  };
}

export function toEndorsementListCbor(v: EndorsementList): Uint8Array {
  return encodeValue(toEndorsementListCborValue(v));
}

export function fromEndorsementListCbor(bytes: Uint8Array): EndorsementList {
  return fromEndorsementListCborValue(decode(bytes));
}

export function toUserSettingsCborValue(v: UserSettings): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.updatedAt !== undefined) csilMap.set("updated_at", { tag: 0, value: csilTsToText(v.updatedAt) });
  csilMap.set("mention_policy", v.mentionPolicy);
  csilMap.set("notify_on_endorse", v.notifyOnEndorse);
  return csilMap;
}

export function fromUserSettingsCborValue(value: CborValue): UserSettings {
  return {
    mentionPolicy: (requireKey(value, "mention_policy") as unknown as MentionPolicy),
    notifyOnEndorse: asBool(requireKey(value, "notify_on_endorse")),
    updatedAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "updated_at")),
  };
}

export function toUserSettingsCbor(v: UserSettings): Uint8Array {
  return encodeValue(toUserSettingsCborValue(v));
}

export function fromUserSettingsCbor(bytes: Uint8Array): UserSettings {
  return fromUserSettingsCborValue(decode(bytes));
}

export function toUpdateSettingsRequestCborValue(v: UpdateSettingsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.mentionPolicy !== undefined) csilMap.set("mention_policy", v.mentionPolicy);
  if (v.notifyOnEndorse !== undefined) csilMap.set("notify_on_endorse", v.notifyOnEndorse);
  return csilMap;
}

export function fromUpdateSettingsRequestCborValue(value: CborValue): UpdateSettingsRequest {
  return {
    mentionPolicy: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : (csilV as unknown as MentionPolicy))(mapGet(value, "mention_policy")),
    notifyOnEndorse: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asBool(csilV))(mapGet(value, "notify_on_endorse")),
  };
}

export function toUpdateSettingsRequestCbor(v: UpdateSettingsRequest): Uint8Array {
  return encodeValue(toUpdateSettingsRequestCborValue(v));
}

export function fromUpdateSettingsRequestCbor(bytes: Uint8Array): UpdateSettingsRequest {
  return fromUpdateSettingsRequestCborValue(decode(bytes));
}

export function toMentionGrantCborValue(v: MentionGrant): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("user_id", v.userId);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  return csilMap;
}

export function fromMentionGrantCborValue(value: CborValue): MentionGrant {
  return {
    userId: asString(requireKey(value, "user_id")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toMentionGrantCbor(v: MentionGrant): Uint8Array {
  return encodeValue(toMentionGrantCborValue(v));
}

export function fromMentionGrantCbor(bytes: Uint8Array): MentionGrant {
  return fromMentionGrantCborValue(decode(bytes));
}

export function toMentionGrantListCborValue(v: MentionGrantList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("grants", v.grants.map((csilE): CborValue => toMentionGrantCborValue(csilE)));
  return csilMap;
}

export function fromMentionGrantListCborValue(value: CborValue): MentionGrantList {
  return {
    grants: asArray(requireKey(value, "grants")).map((csilE) => fromMentionGrantCborValue(csilE)),
  };
}

export function toMentionGrantListCbor(v: MentionGrantList): Uint8Array {
  return encodeValue(toMentionGrantListCborValue(v));
}

export function fromMentionGrantListCbor(bytes: Uint8Array): MentionGrantList {
  return fromMentionGrantListCborValue(decode(bytes));
}

export function toFriendGroupCborValue(v: FriendGroup): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("name", v.name);
  csilMap.set("members", v.members);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  return csilMap;
}

export function fromFriendGroupCborValue(value: CborValue): FriendGroup {
  return {
    id: asString(requireKey(value, "id")),
    name: asString(requireKey(value, "name")),
    members: asArray(requireKey(value, "members")).map((csilE) => asString(csilE)),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toFriendGroupCbor(v: FriendGroup): Uint8Array {
  return encodeValue(toFriendGroupCborValue(v));
}

export function fromFriendGroupCbor(bytes: Uint8Array): FriendGroup {
  return fromFriendGroupCborValue(decode(bytes));
}

export function toFriendGroupListCborValue(v: FriendGroupList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("groups", v.groups.map((csilE): CborValue => toFriendGroupCborValue(csilE)));
  return csilMap;
}

export function fromFriendGroupListCborValue(value: CborValue): FriendGroupList {
  return {
    groups: asArray(requireKey(value, "groups")).map((csilE) => fromFriendGroupCborValue(csilE)),
  };
}

export function toFriendGroupListCbor(v: FriendGroupList): Uint8Array {
  return encodeValue(toFriendGroupListCborValue(v));
}

export function fromFriendGroupListCbor(bytes: Uint8Array): FriendGroupList {
  return fromFriendGroupListCborValue(decode(bytes));
}

export function toCreateFriendGroupRequestCborValue(v: CreateFriendGroupRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("name", v.name);
  return csilMap;
}

export function fromCreateFriendGroupRequestCborValue(value: CborValue): CreateFriendGroupRequest {
  return {
    name: asString(requireKey(value, "name")),
  };
}

export function toCreateFriendGroupRequestCbor(v: CreateFriendGroupRequest): Uint8Array {
  return encodeValue(toCreateFriendGroupRequestCborValue(v));
}

export function fromCreateFriendGroupRequestCbor(bytes: Uint8Array): CreateFriendGroupRequest {
  return fromCreateFriendGroupRequestCborValue(decode(bytes));
}

export function toAddFriendRequestCborValue(v: AddFriendRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("user_id", v.userId);
  csilMap.set("group_id", v.groupId);
  return csilMap;
}

export function fromAddFriendRequestCborValue(value: CborValue): AddFriendRequest {
  return {
    groupId: asString(requireKey(value, "group_id")),
    userId: asString(requireKey(value, "user_id")),
  };
}

export function toAddFriendRequestCbor(v: AddFriendRequest): Uint8Array {
  return encodeValue(toAddFriendRequestCborValue(v));
}

export function fromAddFriendRequestCbor(bytes: Uint8Array): AddFriendRequest {
  return fromAddFriendRequestCborValue(decode(bytes));
}

export function toRemoveFriendRequestCborValue(v: RemoveFriendRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("user_id", v.userId);
  csilMap.set("group_id", v.groupId);
  return csilMap;
}

export function fromRemoveFriendRequestCborValue(value: CborValue): RemoveFriendRequest {
  return {
    groupId: asString(requireKey(value, "group_id")),
    userId: asString(requireKey(value, "user_id")),
  };
}

export function toRemoveFriendRequestCbor(v: RemoveFriendRequest): Uint8Array {
  return encodeValue(toRemoveFriendRequestCborValue(v));
}

export function fromRemoveFriendRequestCbor(bytes: Uint8Array): RemoveFriendRequest {
  return fromRemoveFriendRequestCborValue(decode(bytes));
}

export function toSubscriptionCborValue(v: Subscription): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("muted", v.muted);
  csilMap.set("target_id", v.targetId);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  csilMap.set("target_type", v.targetType);
  return csilMap;
}

export function fromSubscriptionCborValue(value: CborValue): Subscription {
  return {
    id: asString(requireKey(value, "id")),
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
    muted: asBool(requireKey(value, "muted")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toSubscriptionCbor(v: Subscription): Uint8Array {
  return encodeValue(toSubscriptionCborValue(v));
}

export function fromSubscriptionCbor(bytes: Uint8Array): Subscription {
  return fromSubscriptionCborValue(decode(bytes));
}

export function toSetMutedRequestCborValue(v: SetMutedRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("muted", v.muted);
  csilMap.set("target_id", v.targetId);
  csilMap.set("target_type", v.targetType);
  return csilMap;
}

export function fromSetMutedRequestCborValue(value: CborValue): SetMutedRequest {
  return {
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
    muted: asBool(requireKey(value, "muted")),
  };
}

export function toSetMutedRequestCbor(v: SetMutedRequest): Uint8Array {
  return encodeValue(toSetMutedRequestCborValue(v));
}

export function fromSetMutedRequestCbor(bytes: Uint8Array): SetMutedRequest {
  return fromSetMutedRequestCborValue(decode(bytes));
}

export function toSubscriptionListCborValue(v: SubscriptionList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("subscriptions", v.subscriptions.map((csilE): CborValue => toSubscriptionCborValue(csilE)));
  return csilMap;
}

export function fromSubscriptionListCborValue(value: CborValue): SubscriptionList {
  return {
    subscriptions: asArray(requireKey(value, "subscriptions")).map((csilE) => fromSubscriptionCborValue(csilE)),
  };
}

export function toSubscriptionListCbor(v: SubscriptionList): Uint8Array {
  return encodeValue(toSubscriptionListCborValue(v));
}

export function fromSubscriptionListCbor(bytes: Uint8Array): SubscriptionList {
  return fromSubscriptionListCborValue(decode(bytes));
}

export function toBoardUnreadCborValue(v: BoardUnread): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("board_id", v.boardId);
  csilMap.set("unread_count", v.unreadCount);
  csilMap.set("unread_post_ids", v.unreadPostIds);
  return csilMap;
}

export function fromBoardUnreadCborValue(value: CborValue): BoardUnread {
  return {
    boardId: asString(requireKey(value, "board_id")),
    unreadCount: asNumber(requireKey(value, "unread_count")),
    unreadPostIds: asArray(requireKey(value, "unread_post_ids")).map((csilE) => asString(csilE)),
  };
}

export function toBoardUnreadCbor(v: BoardUnread): Uint8Array {
  return encodeValue(toBoardUnreadCborValue(v));
}

export function fromBoardUnreadCbor(bytes: Uint8Array): BoardUnread {
  return fromBoardUnreadCborValue(decode(bytes));
}

export function toUnreadSummaryCborValue(v: UnreadSummary): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("boards", v.boards.map((csilE): CborValue => toBoardUnreadCborValue(csilE)));
  return csilMap;
}

export function fromUnreadSummaryCborValue(value: CborValue): UnreadSummary {
  return {
    boards: asArray(requireKey(value, "boards")).map((csilE) => fromBoardUnreadCborValue(csilE)),
  };
}

export function toUnreadSummaryCbor(v: UnreadSummary): Uint8Array {
  return encodeValue(toUnreadSummaryCborValue(v));
}

export function fromUnreadSummaryCbor(bytes: Uint8Array): UnreadSummary {
  return fromUnreadSummaryCborValue(decode(bytes));
}

export function toNotificationCborValue(v: Notification): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("event", v.event);
  csilMap.set("post_id", v.postId);
  if (v.readAt !== undefined) csilMap.set("read_at", { tag: 0, value: csilTsToText(v.readAt) });
  if (v.actorId !== undefined) csilMap.set("actor_id", v.actorId);
  csilMap.set("target_id", v.targetId);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  csilMap.set("target_type", v.targetType);
  return csilMap;
}

export function fromNotificationCborValue(value: CborValue): Notification {
  return {
    id: asString(requireKey(value, "id")),
    event: (requireKey(value, "event") as unknown as NotificationEvent),
    actorId: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "actor_id")),
    targetType: (requireKey(value, "target_type") as unknown as TargetType),
    targetId: asString(requireKey(value, "target_id")),
    postId: asString(requireKey(value, "post_id")),
    readAt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asTimestamp(csilV))(mapGet(value, "read_at")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toNotificationCbor(v: Notification): Uint8Array {
  return encodeValue(toNotificationCborValue(v));
}

export function fromNotificationCbor(bytes: Uint8Array): Notification {
  return fromNotificationCborValue(decode(bytes));
}

export function toListNotificationsRequestCborValue(v: ListNotificationsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.limit !== undefined) csilMap.set("limit", v.limit);
  if (v.cursor !== undefined) csilMap.set("cursor", v.cursor);
  if (v.unreadOnly !== undefined) csilMap.set("unread_only", v.unreadOnly);
  return csilMap;
}

export function fromListNotificationsRequestCborValue(value: CborValue): ListNotificationsRequest {
  return {
    cursor: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "cursor")),
    limit: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asNumber(csilV))(mapGet(value, "limit")),
    unreadOnly: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asBool(csilV))(mapGet(value, "unread_only")),
  };
}

export function toListNotificationsRequestCbor(v: ListNotificationsRequest): Uint8Array {
  return encodeValue(toListNotificationsRequestCborValue(v));
}

export function fromListNotificationsRequestCbor(bytes: Uint8Array): ListNotificationsRequest {
  return fromListNotificationsRequestCborValue(decode(bytes));
}

export function toNotificationPageCborValue(v: NotificationPage): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.nextCursor !== undefined) csilMap.set("next_cursor", v.nextCursor);
  csilMap.set("notifications", v.notifications.map((csilE): CborValue => toNotificationCborValue(csilE)));
  return csilMap;
}

export function fromNotificationPageCborValue(value: CborValue): NotificationPage {
  return {
    notifications: asArray(requireKey(value, "notifications")).map((csilE) => fromNotificationCborValue(csilE)),
    nextCursor: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "next_cursor")),
  };
}

export function toNotificationPageCbor(v: NotificationPage): Uint8Array {
  return encodeValue(toNotificationPageCborValue(v));
}

export function fromNotificationPageCbor(bytes: Uint8Array): NotificationPage {
  return fromNotificationPageCborValue(decode(bytes));
}

export function toGithubMappingCborValue(v: GithubMapping): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("id", v.id);
  csilMap.set("repo", v.repo);
  csilMap.set("events", v.events);
  csilMap.set("board_id", v.boardId);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  csilMap.set("created_by", v.createdBy);
  csilMap.set("thread_mode", v.threadMode);
  return csilMap;
}

export function fromGithubMappingCborValue(value: CborValue): GithubMapping {
  return {
    id: asString(requireKey(value, "id")),
    boardId: asString(requireKey(value, "board_id")),
    repo: asString(requireKey(value, "repo")),
    events: asArray(requireKey(value, "events")).map((csilE) => asString(csilE)),
    threadMode: (requireKey(value, "thread_mode") as unknown as ThreadMode),
    createdBy: asString(requireKey(value, "created_by")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toGithubMappingCbor(v: GithubMapping): Uint8Array {
  return encodeValue(toGithubMappingCborValue(v));
}

export function fromGithubMappingCbor(bytes: Uint8Array): GithubMapping {
  return fromGithubMappingCborValue(decode(bytes));
}

export function toCreateMappingRequestCborValue(v: CreateMappingRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("repo", v.repo);
  csilMap.set("events", v.events);
  csilMap.set("board_id", v.boardId);
  csilMap.set("secret_ref", v.secretRef);
  csilMap.set("thread_mode", v.threadMode);
  return csilMap;
}

export function fromCreateMappingRequestCborValue(value: CborValue): CreateMappingRequest {
  return {
    boardId: asString(requireKey(value, "board_id")),
    repo: asString(requireKey(value, "repo")),
    events: asArray(requireKey(value, "events")).map((csilE) => asString(csilE)),
    secretRef: asString(requireKey(value, "secret_ref")),
    threadMode: (requireKey(value, "thread_mode") as unknown as ThreadMode),
  };
}

export function toCreateMappingRequestCbor(v: CreateMappingRequest): Uint8Array {
  return encodeValue(toCreateMappingRequestCborValue(v));
}

export function fromCreateMappingRequestCbor(bytes: Uint8Array): CreateMappingRequest {
  return fromCreateMappingRequestCborValue(decode(bytes));
}

export function toMappingListCborValue(v: MappingList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("mappings", v.mappings.map((csilE): CborValue => toGithubMappingCborValue(csilE)));
  return csilMap;
}

export function fromMappingListCborValue(value: CborValue): MappingList {
  return {
    mappings: asArray(requireKey(value, "mappings")).map((csilE) => fromGithubMappingCborValue(csilE)),
  };
}

export function toMappingListCbor(v: MappingList): Uint8Array {
  return encodeValue(toMappingListCborValue(v));
}

export function fromMappingListCbor(bytes: Uint8Array): MappingList {
  return fromMappingListCborValue(decode(bytes));
}

export function toDomainEntryCborValue(v: DomainEntry): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("domain", v.domain);
  csilMap.set("added_by", v.addedBy);
  csilMap.set("created_at", { tag: 0, value: csilTsToText(v.createdAt) });
  return csilMap;
}

export function fromDomainEntryCborValue(value: CborValue): DomainEntry {
  return {
    domain: asString(requireKey(value, "domain")),
    addedBy: asString(requireKey(value, "added_by")),
    createdAt: asTimestamp(requireKey(value, "created_at")),
  };
}

export function toDomainEntryCbor(v: DomainEntry): Uint8Array {
  return encodeValue(toDomainEntryCborValue(v));
}

export function fromDomainEntryCbor(bytes: Uint8Array): DomainEntry {
  return fromDomainEntryCborValue(decode(bytes));
}

export function toDomainListCborValue(v: DomainList): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("domains", v.domains.map((csilE): CborValue => toDomainEntryCborValue(csilE)));
  return csilMap;
}

export function fromDomainListCborValue(value: CborValue): DomainList {
  return {
    domains: asArray(requireKey(value, "domains")).map((csilE) => fromDomainEntryCborValue(csilE)),
  };
}

export function toDomainListCbor(v: DomainList): Uint8Array {
  return encodeValue(toDomainListCborValue(v));
}

export function fromDomainListCbor(bytes: Uint8Array): DomainList {
  return fromDomainListCborValue(decode(bytes));
}

