// Package csil contains generated constructor functions.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

// NewListBoardsRequest creates a ListBoardsRequest with default values:
//   - limit: 50
func NewListBoardsRequest() *ListBoardsRequest {
	return &ListBoardsRequest{
		Limit: func() *uint64 { v := uint64(50); return &v }(),
	}
}

// NewListPostsRequest creates a ListPostsRequest with default values:
//   - limit: 50
func NewListPostsRequest() *ListPostsRequest {
	return &ListPostsRequest{
		Limit: func() *uint64 { v := uint64(50); return &v }(),
	}
}

// NewUserSettings creates a UserSettings with default values:
//   - mention_policy: "subscribed"
//   - notify_on_endorse: true
func NewUserSettings() *UserSettings {
	return &UserSettings{
		MentionPolicy:   "subscribed",
		NotifyOnEndorse: true,
	}
}

// NewSubscription creates a Subscription with default values:
//   - muted: false
func NewSubscription() *Subscription {
	return &Subscription{
		Muted: false,
	}
}

// NewListNotificationsRequest creates a ListNotificationsRequest with default values:
//   - limit: 50
//   - unread_only: false
func NewListNotificationsRequest() *ListNotificationsRequest {
	return &ListNotificationsRequest{
		Limit:      func() *uint64 { v := uint64(50); return &v }(),
		UnreadOnly: func() *bool { v := bool(false); return &v }(),
	}
}
