// Package csil contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"context"
)

// AuthService defines the service interface
type AuthService interface {
	BeginLogin(ctx context.Context, req BeginLoginRequest) (interface{}, error)
	Logout(ctx context.Context, req Empty) (Empty, error)
	Whoami(ctx context.Context, req Empty) (interface{}, error)
}

// Wire-id ordinals for the AuthService service (transport compact profiles).
const AuthServiceServiceWireID uint64 = 1
const AuthServiceOpBeginLoginWireID uint64 = 0
const AuthServiceOpLogoutWireID uint64 = 1
const AuthServiceOpWhoamiWireID uint64 = 2

// BoardService defines the service interface
type BoardService interface {
	ListBoards(ctx context.Context, req ListBoardsRequest) (BoardPage, error)
	GetBoard(ctx context.Context, req BoardSlug) (interface{}, error)
	CreateBoard(ctx context.Context, req CreateBoardRequest) (interface{}, error)
	UpdateBoard(ctx context.Context, req UpdateBoardRequest) (interface{}, error)
	ArchiveBoard(ctx context.Context, req BoardID) (interface{}, error)
	SetBoardMember(ctx context.Context, req SetBoardMemberRequest) (interface{}, error)
	RemoveBoardMember(ctx context.Context, req RemoveBoardMemberRequest) (interface{}, error)
}

// Wire-id ordinals for the BoardService service (transport compact profiles).
const BoardServiceServiceWireID uint64 = 2
const BoardServiceOpListBoardsWireID uint64 = 0
const BoardServiceOpGetBoardWireID uint64 = 1
const BoardServiceOpCreateBoardWireID uint64 = 2
const BoardServiceOpUpdateBoardWireID uint64 = 3
const BoardServiceOpArchiveBoardWireID uint64 = 4
const BoardServiceOpSetBoardMemberWireID uint64 = 5
const BoardServiceOpRemoveBoardMemberWireID uint64 = 6

// ThreadService defines the service interface
type ThreadService interface {
	ListPosts(ctx context.Context, req ListPostsRequest) (PostPage, error)
	GetThread(ctx context.Context, req GetThreadRequest) (Thread, error)
	CreatePost(ctx context.Context, req CreatePostRequest) (interface{}, error)
	CreateComment(ctx context.Context, req CreateCommentRequest) (interface{}, error)
	EditPost(ctx context.Context, req EditPostRequest) (interface{}, error)
	EditComment(ctx context.Context, req EditCommentRequest) (interface{}, error)
	ListRevisions(ctx context.Context, req TargetRef) (RevisionList, error)
	DeletePost(ctx context.Context, req PostID) (interface{}, error)
	DeleteComment(ctx context.Context, req CommentID) (interface{}, error)
}

// Wire-id ordinals for the ThreadService service (transport compact profiles).
const ThreadServiceServiceWireID uint64 = 3
const ThreadServiceOpListPostsWireID uint64 = 0
const ThreadServiceOpGetThreadWireID uint64 = 1
const ThreadServiceOpCreatePostWireID uint64 = 2
const ThreadServiceOpCreateCommentWireID uint64 = 3
const ThreadServiceOpEditPostWireID uint64 = 4
const ThreadServiceOpEditCommentWireID uint64 = 5
const ThreadServiceOpListRevisionsWireID uint64 = 6
const ThreadServiceOpDeletePostWireID uint64 = 7
const ThreadServiceOpDeleteCommentWireID uint64 = 8

// EndorsementService defines the service interface
type EndorsementService interface {
	Endorse(ctx context.Context, req EndorseRequest) (interface{}, error)
	Retract(ctx context.Context, req EndorseRequest) (interface{}, error)
	ListEndorsements(ctx context.Context, req TargetRef) (EndorsementList, error)
}

// Wire-id ordinals for the EndorsementService service (transport compact profiles).
const EndorsementServiceServiceWireID uint64 = 4
const EndorsementServiceOpEndorseWireID uint64 = 0
const EndorsementServiceOpRetractWireID uint64 = 1
const EndorsementServiceOpListEndorsementsWireID uint64 = 2

// SettingsService defines the service interface
type SettingsService interface {
	GetSettings(ctx context.Context, req Empty) (UserSettings, error)
	UpdateSettings(ctx context.Context, req UpdateSettingsRequest) (interface{}, error)
	ListMentionGrants(ctx context.Context, req Empty) (MentionGrantList, error)
	GrantMention(ctx context.Context, req UserID) (interface{}, error)
	RevokeMention(ctx context.Context, req UserID) (interface{}, error)
}

// Wire-id ordinals for the SettingsService service (transport compact profiles).
const SettingsServiceServiceWireID uint64 = 5
const SettingsServiceOpGetSettingsWireID uint64 = 0
const SettingsServiceOpUpdateSettingsWireID uint64 = 1
const SettingsServiceOpListMentionGrantsWireID uint64 = 2
const SettingsServiceOpGrantMentionWireID uint64 = 3
const SettingsServiceOpRevokeMentionWireID uint64 = 4

// SocialService defines the service interface
type SocialService interface {
	ListFriendGroups(ctx context.Context, req Empty) (FriendGroupList, error)
	CreateFriendGroup(ctx context.Context, req CreateFriendGroupRequest) (interface{}, error)
	DeleteFriendGroup(ctx context.Context, req GroupID) (interface{}, error)
	AddFriend(ctx context.Context, req AddFriendRequest) (interface{}, error)
	RemoveFriend(ctx context.Context, req RemoveFriendRequest) (interface{}, error)
}

// Wire-id ordinals for the SocialService service (transport compact profiles).
const SocialServiceServiceWireID uint64 = 6
const SocialServiceOpListFriendGroupsWireID uint64 = 0
const SocialServiceOpCreateFriendGroupWireID uint64 = 1
const SocialServiceOpDeleteFriendGroupWireID uint64 = 2
const SocialServiceOpAddFriendWireID uint64 = 3
const SocialServiceOpRemoveFriendWireID uint64 = 4

// SubscriptionService defines the service interface
type SubscriptionService interface {
	Subscribe(ctx context.Context, req TargetRef) (interface{}, error)
	Unsubscribe(ctx context.Context, req TargetRef) (interface{}, error)
	SetMuted(ctx context.Context, req SetMutedRequest) (interface{}, error)
	ListSubscriptions(ctx context.Context, req Empty) (SubscriptionList, error)
}

// Wire-id ordinals for the SubscriptionService service (transport compact profiles).
const SubscriptionServiceServiceWireID uint64 = 7
const SubscriptionServiceOpSubscribeWireID uint64 = 0
const SubscriptionServiceOpUnsubscribeWireID uint64 = 1
const SubscriptionServiceOpSetMutedWireID uint64 = 2
const SubscriptionServiceOpListSubscriptionsWireID uint64 = 3

// ReadService defines the service interface
type ReadService interface {
	MarkRead(ctx context.Context, req TargetRef) (Empty, error)
	MarkUnread(ctx context.Context, req TargetRef) (Empty, error)
	UnreadSummary(ctx context.Context, req Empty) (UnreadSummary, error)
}

// Wire-id ordinals for the ReadService service (transport compact profiles).
const ReadServiceServiceWireID uint64 = 8
const ReadServiceOpMarkReadWireID uint64 = 0
const ReadServiceOpMarkUnreadWireID uint64 = 1
const ReadServiceOpUnreadSummaryWireID uint64 = 2

// NotificationService defines the service interface
type NotificationService interface {
	ListNotifications(ctx context.Context, req ListNotificationsRequest) (NotificationPage, error)
	MarkNotificationRead(ctx context.Context, req NotificationIDs) (Empty, error)
	MarkAllRead(ctx context.Context, req Empty) (Empty, error)
}

// Wire-id ordinals for the NotificationService service (transport compact profiles).
const NotificationServiceServiceWireID uint64 = 9
const NotificationServiceOpListNotificationsWireID uint64 = 0
const NotificationServiceOpMarkNotificationReadWireID uint64 = 1
const NotificationServiceOpMarkAllReadWireID uint64 = 2

// IntegrationService defines the service interface
type IntegrationService interface {
	CreateGithubMapping(ctx context.Context, req CreateMappingRequest) (interface{}, error)
	ListGithubMappings(ctx context.Context, req Empty) (MappingList, error)
	DeleteGithubMapping(ctx context.Context, req MappingID) (interface{}, error)
	AddTrustedDomain(ctx context.Context, req Domain) (interface{}, error)
	RemoveTrustedDomain(ctx context.Context, req Domain) (interface{}, error)
	ListTrustedDomains(ctx context.Context, req Empty) (DomainList, error)
}

// Wire-id ordinals for the IntegrationService service (transport compact profiles).
const IntegrationServiceServiceWireID uint64 = 10
const IntegrationServiceOpCreateGithubMappingWireID uint64 = 0
const IntegrationServiceOpListGithubMappingsWireID uint64 = 1
const IntegrationServiceOpDeleteGithubMappingWireID uint64 = 2
const IntegrationServiceOpAddTrustedDomainWireID uint64 = 3
const IntegrationServiceOpRemoveTrustedDomainWireID uint64 = 4
const IntegrationServiceOpListTrustedDomainsWireID uint64 = 5
