// Package csil contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"time"
)

// UserID is a type alias
type UserID string

// BoardID is a type alias
type BoardID string

// PostID is a type alias
type PostID string

// CommentID is a type alias
type CommentID string

// RevisionID is a type alias
type RevisionID string

// EndorsementID is a type alias
type EndorsementID string

// SubscriptionID is a type alias
type SubscriptionID string

// GroupID is a type alias
type GroupID string

// NotificationID is a type alias
type NotificationID string

// MappingID is a type alias
type MappingID string

// PageCursor is a type alias
type PageCursor string

// TargetType is a type alias
type TargetType string

// TargetRef represents a structured data type
type TargetRef struct {
	TargetType TargetType `json:"target_type" yaml:"target_type"`
	TargetId   string     `json:"target_id" yaml:"target_id"`
}

// OriginKind is a type alias
type OriginKind string

// Empty represents a structured data type
type Empty struct {
}

// ServiceError represents a structured data type
type ServiceError struct {
	Code         uint64  `json:"code" yaml:"code"`
	Message      string  `json:"message" yaml:"message"`
	Field        *string `json:"field,omitempty" yaml:"field,omitempty"`
	ResourceType *string `json:"resource_type,omitempty" yaml:"resource_type,omitempty"`
}

// UserKind is a type alias
type UserKind string

// BeginLoginRequest represents a structured data type
type BeginLoginRequest struct {
	Domain string `json:"domain" yaml:"domain"`
}

// BeginLoginResponse represents a structured data type
type BeginLoginResponse struct {
	RedirectUrl string `json:"redirect_url" yaml:"redirect_url"`
}

// UserProfile represents a structured data type
type UserProfile struct {
	Id             UserID    `json:"id" yaml:"id"`
	LinkkeysDomain string    `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	Handle         string    `json:"handle" yaml:"handle"`
	DisplayName    string    `json:"display_name" yaml:"display_name"`
	Kind           UserKind  `json:"kind" yaml:"kind"`
	Roles          []string  `json:"roles" yaml:"roles"`
	CreatedAt      time.Time `json:"created_at" yaml:"created_at"`
}

// BoardKind is a type alias
type BoardKind string

// BoardRole is a type alias
type BoardRole string

// BoardSlug is a type alias
type BoardSlug string

// Board represents a structured data type
type Board struct {
	Id          BoardID    `json:"id" yaml:"id"`
	Slug        string     `json:"slug" yaml:"slug"`
	Title       string     `json:"title" yaml:"title"`
	Description *string    `json:"description,omitempty" yaml:"description,omitempty"`
	Kind        BoardKind  `json:"kind" yaml:"kind"`
	CreatedBy   UserID     `json:"created_by" yaml:"created_by"`
	ArchivedAt  *time.Time `json:"archived_at,omitempty" yaml:"archived_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at" yaml:"created_at"`
}

// ListBoardsRequest represents a structured data type
type ListBoardsRequest struct {
	Cursor *PageCursor `json:"cursor,omitempty" yaml:"cursor,omitempty"`
	Limit  *uint64     `json:"limit,omitempty" yaml:"limit,omitempty"`
}

// BoardPage represents a structured data type
type BoardPage struct {
	Boards     []Board     `json:"boards" yaml:"boards"`
	NextCursor *PageCursor `json:"next_cursor,omitempty" yaml:"next_cursor,omitempty"`
}

// CreateBoardRequest represents a structured data type
type CreateBoardRequest struct {
	Slug        string    `json:"slug" yaml:"slug"`
	Title       string    `json:"title" yaml:"title"`
	Description *string   `json:"description,omitempty" yaml:"description,omitempty"`
	Kind        BoardKind `json:"kind" yaml:"kind"`
}

// UpdateBoardRequest represents a structured data type
type UpdateBoardRequest struct {
	Id          BoardID `json:"id" yaml:"id"`
	Title       *string `json:"title,omitempty" yaml:"title,omitempty"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// SetBoardMemberRequest represents a structured data type
type SetBoardMemberRequest struct {
	BoardId BoardID   `json:"board_id" yaml:"board_id"`
	UserId  UserID    `json:"user_id" yaml:"user_id"`
	Role    BoardRole `json:"role" yaml:"role"`
}

// RemoveBoardMemberRequest represents a structured data type
type RemoveBoardMemberRequest struct {
	BoardId BoardID `json:"board_id" yaml:"board_id"`
	UserId  UserID  `json:"user_id" yaml:"user_id"`
}

// Post represents a structured data type
type Post struct {
	Id             PostID     `json:"id" yaml:"id"`
	BoardId        BoardID    `json:"board_id" yaml:"board_id"`
	AuthorId       UserID     `json:"author_id" yaml:"author_id"`
	Title          string     `json:"title" yaml:"title"`
	BodyMd         string     `json:"body_md" yaml:"body_md"`
	Origin         OriginKind `json:"origin" yaml:"origin"`
	OriginRef      *string    `json:"origin_ref,omitempty" yaml:"origin_ref,omitempty"`
	CommentCount   uint64     `json:"comment_count" yaml:"comment_count"`
	LastActivityAt time.Time  `json:"last_activity_at" yaml:"last_activity_at"`
	EditedAt       *time.Time `json:"edited_at,omitempty" yaml:"edited_at,omitempty"`
	DeletedAt      *time.Time `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	CreatedAt      time.Time  `json:"created_at" yaml:"created_at"`
}

// Comment represents a structured data type
type Comment struct {
	Id              CommentID  `json:"id" yaml:"id"`
	PostId          PostID     `json:"post_id" yaml:"post_id"`
	ParentCommentId *CommentID `json:"parent_comment_id,omitempty" yaml:"parent_comment_id,omitempty"`
	AuthorId        UserID     `json:"author_id" yaml:"author_id"`
	BodyMd          string     `json:"body_md" yaml:"body_md"`
	Origin          OriginKind `json:"origin" yaml:"origin"`
	OriginRef       *string    `json:"origin_ref,omitempty" yaml:"origin_ref,omitempty"`
	EditedAt        *time.Time `json:"edited_at,omitempty" yaml:"edited_at,omitempty"`
	DeletedAt       *time.Time `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	CreatedAt       time.Time  `json:"created_at" yaml:"created_at"`
}

// ListPostsRequest represents a structured data type
type ListPostsRequest struct {
	BoardId BoardID     `json:"board_id" yaml:"board_id"`
	Cursor  *PageCursor `json:"cursor,omitempty" yaml:"cursor,omitempty"`
	Limit   *uint64     `json:"limit,omitempty" yaml:"limit,omitempty"`
}

// PostPage represents a structured data type
type PostPage struct {
	Posts      []Post      `json:"posts" yaml:"posts"`
	NextCursor *PageCursor `json:"next_cursor,omitempty" yaml:"next_cursor,omitempty"`
}

// GetThreadRequest represents a structured data type
type GetThreadRequest struct {
	PostId PostID `json:"post_id" yaml:"post_id"`
}

// Thread represents a structured data type
type Thread struct {
	Post     Post      `json:"post" yaml:"post"`
	Comments []Comment `json:"comments" yaml:"comments"`
}

// CreatePostRequest represents a structured data type
type CreatePostRequest struct {
	BoardId BoardID `json:"board_id" yaml:"board_id"`
	Title   string  `json:"title" yaml:"title"`
	BodyMd  string  `json:"body_md" yaml:"body_md"`
}

// CreateCommentRequest represents a structured data type
type CreateCommentRequest struct {
	PostId          PostID     `json:"post_id" yaml:"post_id"`
	ParentCommentId *CommentID `json:"parent_comment_id,omitempty" yaml:"parent_comment_id,omitempty"`
	BodyMd          string     `json:"body_md" yaml:"body_md"`
}

// EditPostRequest represents a structured data type
type EditPostRequest struct {
	Id     PostID `json:"id" yaml:"id"`
	Title  string `json:"title" yaml:"title"`
	BodyMd string `json:"body_md" yaml:"body_md"`
}

// EditCommentRequest represents a structured data type
type EditCommentRequest struct {
	Id     CommentID `json:"id" yaml:"id"`
	BodyMd string    `json:"body_md" yaml:"body_md"`
}

// Revision represents a structured data type
type Revision struct {
	Id         RevisionID `json:"id" yaml:"id"`
	TargetType TargetType `json:"target_type" yaml:"target_type"`
	TargetId   string     `json:"target_id" yaml:"target_id"`
	EditorId   UserID     `json:"editor_id" yaml:"editor_id"`
	PrevTitle  *string    `json:"prev_title,omitempty" yaml:"prev_title,omitempty"`
	PrevBodyMd string     `json:"prev_body_md" yaml:"prev_body_md"`
	CreatedAt  time.Time  `json:"created_at" yaml:"created_at"`
}

// RevisionList represents a structured data type
type RevisionList struct {
	Revisions []Revision `json:"revisions" yaml:"revisions"`
}

// EndorseRequest represents a structured data type
type EndorseRequest struct {
	TargetType TargetType `json:"target_type" yaml:"target_type"`
	TargetId   string     `json:"target_id" yaml:"target_id"`
}

// Endorsement represents a structured data type
type Endorsement struct {
	Id         EndorsementID `json:"id" yaml:"id"`
	UserId     UserID        `json:"user_id" yaml:"user_id"`
	TargetType TargetType    `json:"target_type" yaml:"target_type"`
	TargetId   string        `json:"target_id" yaml:"target_id"`
	RoleBadge  *string       `json:"role_badge,omitempty" yaml:"role_badge,omitempty"`
	CreatedAt  time.Time     `json:"created_at" yaml:"created_at"`
}

// EndorsementList represents a structured data type
type EndorsementList struct {
	Endorsements []Endorsement `json:"endorsements" yaml:"endorsements"`
}

// MentionPolicy is a type alias
type MentionPolicy string

// UserSettings represents a structured data type
type UserSettings struct {
	MentionPolicy   MentionPolicy `json:"mention_policy" yaml:"mention_policy"`
	NotifyOnEndorse bool          `json:"notify_on_endorse" yaml:"notify_on_endorse"`
	UpdatedAt       *time.Time    `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
}

// UpdateSettingsRequest represents a structured data type
type UpdateSettingsRequest struct {
	MentionPolicy   *MentionPolicy `json:"mention_policy,omitempty" yaml:"mention_policy,omitempty"`
	NotifyOnEndorse *bool          `json:"notify_on_endorse,omitempty" yaml:"notify_on_endorse,omitempty"`
}

// MentionGrant represents a structured data type
type MentionGrant struct {
	UserId    UserID    `json:"user_id" yaml:"user_id"`
	CreatedAt time.Time `json:"created_at" yaml:"created_at"`
}

// MentionGrantList represents a structured data type
type MentionGrantList struct {
	Grants []MentionGrant `json:"grants" yaml:"grants"`
}

// FriendGroup represents a structured data type
type FriendGroup struct {
	Id        GroupID   `json:"id" yaml:"id"`
	Name      string    `json:"name" yaml:"name"`
	Members   []UserID  `json:"members" yaml:"members"`
	CreatedAt time.Time `json:"created_at" yaml:"created_at"`
}

// FriendGroupList represents a structured data type
type FriendGroupList struct {
	Groups []FriendGroup `json:"groups" yaml:"groups"`
}

// CreateFriendGroupRequest represents a structured data type
type CreateFriendGroupRequest struct {
	Name string `json:"name" yaml:"name"`
}

// AddFriendRequest represents a structured data type
type AddFriendRequest struct {
	GroupId GroupID `json:"group_id" yaml:"group_id"`
	UserId  UserID  `json:"user_id" yaml:"user_id"`
}

// RemoveFriendRequest represents a structured data type
type RemoveFriendRequest struct {
	GroupId GroupID `json:"group_id" yaml:"group_id"`
	UserId  UserID  `json:"user_id" yaml:"user_id"`
}

// Subscription represents a structured data type
type Subscription struct {
	Id         SubscriptionID `json:"id" yaml:"id"`
	TargetType TargetType     `json:"target_type" yaml:"target_type"`
	TargetId   string         `json:"target_id" yaml:"target_id"`
	Muted      bool           `json:"muted" yaml:"muted"`
	CreatedAt  time.Time      `json:"created_at" yaml:"created_at"`
}

// SetMutedRequest represents a structured data type
type SetMutedRequest struct {
	TargetType TargetType `json:"target_type" yaml:"target_type"`
	TargetId   string     `json:"target_id" yaml:"target_id"`
	Muted      bool       `json:"muted" yaml:"muted"`
}

// SubscriptionList represents a structured data type
type SubscriptionList struct {
	Subscriptions []Subscription `json:"subscriptions" yaml:"subscriptions"`
}

// BoardUnread represents a structured data type
type BoardUnread struct {
	BoardId       BoardID  `json:"board_id" yaml:"board_id"`
	UnreadCount   uint64   `json:"unread_count" yaml:"unread_count"`
	UnreadPostIds []PostID `json:"unread_post_ids" yaml:"unread_post_ids"`
}

// UnreadSummary represents a structured data type
type UnreadSummary struct {
	Boards []BoardUnread `json:"boards" yaml:"boards"`
}

// NotificationEvent is a type alias
type NotificationEvent string

// Notification represents a structured data type
type Notification struct {
	Id         NotificationID    `json:"id" yaml:"id"`
	Event      NotificationEvent `json:"event" yaml:"event"`
	ActorId    *UserID           `json:"actor_id,omitempty" yaml:"actor_id,omitempty"`
	TargetType TargetType        `json:"target_type" yaml:"target_type"`
	TargetId   string            `json:"target_id" yaml:"target_id"`
	PostId     PostID            `json:"post_id" yaml:"post_id"`
	ReadAt     *time.Time        `json:"read_at,omitempty" yaml:"read_at,omitempty"`
	CreatedAt  time.Time         `json:"created_at" yaml:"created_at"`
}

// ListNotificationsRequest represents a structured data type
type ListNotificationsRequest struct {
	Cursor     *PageCursor `json:"cursor,omitempty" yaml:"cursor,omitempty"`
	Limit      *uint64     `json:"limit,omitempty" yaml:"limit,omitempty"`
	UnreadOnly *bool       `json:"unread_only,omitempty" yaml:"unread_only,omitempty"`
}

// NotificationPage represents a structured data type
type NotificationPage struct {
	Notifications []Notification `json:"notifications" yaml:"notifications"`
	NextCursor    *PageCursor    `json:"next_cursor,omitempty" yaml:"next_cursor,omitempty"`
}

// NotificationIDs is a type alias
type NotificationIDs []NotificationID

// ThreadMode is a type alias
type ThreadMode string

// GithubMapping represents a structured data type
type GithubMapping struct {
	Id         MappingID  `json:"id" yaml:"id"`
	BoardId    BoardID    `json:"board_id" yaml:"board_id"`
	Repo       string     `json:"repo" yaml:"repo"`
	Events     []string   `json:"events" yaml:"events"`
	ThreadMode ThreadMode `json:"thread_mode" yaml:"thread_mode"`
	CreatedBy  UserID     `json:"created_by" yaml:"created_by"`
	CreatedAt  time.Time  `json:"created_at" yaml:"created_at"`
}

// CreateMappingRequest represents a structured data type
type CreateMappingRequest struct {
	BoardId    BoardID    `json:"board_id" yaml:"board_id"`
	Repo       string     `json:"repo" yaml:"repo"`
	Events     []string   `json:"events" yaml:"events"`
	SecretRef  string     `json:"secret_ref" yaml:"secret_ref"`
	ThreadMode ThreadMode `json:"thread_mode" yaml:"thread_mode"`
}

// MappingList represents a structured data type
type MappingList struct {
	Mappings []GithubMapping `json:"mappings" yaml:"mappings"`
}

// Domain is a type alias
type Domain string

// DomainEntry represents a structured data type
type DomainEntry struct {
	Domain    string    `json:"domain" yaml:"domain"`
	AddedBy   UserID    `json:"added_by" yaml:"added_by"`
	CreatedAt time.Time `json:"created_at" yaml:"created_at"`
}

// DomainList represents a structured data type
type DomainList struct {
	Domains []DomainEntry `json:"domains" yaml:"domains"`
}
