// Package csil contains generated validation functions.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"fmt"
	"regexp"
)

// ValidateBeginLoginRequest validates the BeginLoginRequest struct
func (v *BeginLoginRequest) Validate() error {
	if len(v.Domain) < 1 {
		return fmt.Errorf("field 'Domain' must have at least 1 elements")
	}
	if len(v.Domain) > 253 {
		return fmt.Errorf("field 'Domain' must have at most 253 elements")
	}
	return nil
}

// ValidateBoard validates the Board struct
func (v *Board) Validate() error {
	if len(v.Slug) < 1 {
		return fmt.Errorf("field 'Slug' must have at least 1 elements")
	}
	if len(v.Slug) > 64 {
		return fmt.Errorf("field 'Slug' must have at most 64 elements")
	}
	matched, _ := regexp.MatchString(`^[a-z0-9]+(-[a-z0-9]+)*$`, v.Slug)
	if !matched {
		return fmt.Errorf("field 'Slug' must match pattern '^[a-z0-9]+(-[a-z0-9]+)*$'")
	}
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 256 {
		return fmt.Errorf("field 'Title' must have at most 256 elements")
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 2000 {
			return fmt.Errorf("field 'Description' must have at most 2000 elements")
		}
	}
	return nil
}

// ValidateListBoardsRequest validates the ListBoardsRequest struct
func (v *ListBoardsRequest) Validate() error {
	if v.Limit != nil {
		if (*v.Limit) > 200 {
			return fmt.Errorf("field 'Limit' must be <= 200")
		}
	}
	return nil
}

// ValidateCreateBoardRequest validates the CreateBoardRequest struct
func (v *CreateBoardRequest) Validate() error {
	if len(v.Slug) < 1 {
		return fmt.Errorf("field 'Slug' must have at least 1 elements")
	}
	if len(v.Slug) > 64 {
		return fmt.Errorf("field 'Slug' must have at most 64 elements")
	}
	matched, _ := regexp.MatchString(`^[a-z0-9]+(-[a-z0-9]+)*$`, v.Slug)
	if !matched {
		return fmt.Errorf("field 'Slug' must match pattern '^[a-z0-9]+(-[a-z0-9]+)*$'")
	}
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 256 {
		return fmt.Errorf("field 'Title' must have at most 256 elements")
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 2000 {
			return fmt.Errorf("field 'Description' must have at most 2000 elements")
		}
	}
	return nil
}

// ValidateUpdateBoardRequest validates the UpdateBoardRequest struct
func (v *UpdateBoardRequest) Validate() error {
	if v.Title != nil {
		if len((*v.Title)) < 1 {
			return fmt.Errorf("field 'Title' must have at least 1 elements")
		}
	}
	if v.Title != nil {
		if len((*v.Title)) > 256 {
			return fmt.Errorf("field 'Title' must have at most 256 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 2000 {
			return fmt.Errorf("field 'Description' must have at most 2000 elements")
		}
	}
	return nil
}

// ValidatePost validates the Post struct
func (v *Post) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 512 {
		return fmt.Errorf("field 'Title' must have at most 512 elements")
	}
	if len(v.BodyMd) < 1 {
		return fmt.Errorf("field 'BodyMd' must have at least 1 elements")
	}
	if len(v.BodyMd) > 100000 {
		return fmt.Errorf("field 'BodyMd' must have at most 100000 elements")
	}
	return nil
}

// ValidateComment validates the Comment struct
func (v *Comment) Validate() error {
	if len(v.BodyMd) < 1 {
		return fmt.Errorf("field 'BodyMd' must have at least 1 elements")
	}
	if len(v.BodyMd) > 100000 {
		return fmt.Errorf("field 'BodyMd' must have at most 100000 elements")
	}
	return nil
}

// ValidateListPostsRequest validates the ListPostsRequest struct
func (v *ListPostsRequest) Validate() error {
	if v.Limit != nil {
		if (*v.Limit) > 200 {
			return fmt.Errorf("field 'Limit' must be <= 200")
		}
	}
	return nil
}

// ValidateCreatePostRequest validates the CreatePostRequest struct
func (v *CreatePostRequest) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 512 {
		return fmt.Errorf("field 'Title' must have at most 512 elements")
	}
	if len(v.BodyMd) < 1 {
		return fmt.Errorf("field 'BodyMd' must have at least 1 elements")
	}
	if len(v.BodyMd) > 100000 {
		return fmt.Errorf("field 'BodyMd' must have at most 100000 elements")
	}
	return nil
}

// ValidateCreateCommentRequest validates the CreateCommentRequest struct
func (v *CreateCommentRequest) Validate() error {
	if len(v.BodyMd) < 1 {
		return fmt.Errorf("field 'BodyMd' must have at least 1 elements")
	}
	if len(v.BodyMd) > 100000 {
		return fmt.Errorf("field 'BodyMd' must have at most 100000 elements")
	}
	return nil
}

// ValidateEditPostRequest validates the EditPostRequest struct
func (v *EditPostRequest) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 512 {
		return fmt.Errorf("field 'Title' must have at most 512 elements")
	}
	if len(v.BodyMd) < 1 {
		return fmt.Errorf("field 'BodyMd' must have at least 1 elements")
	}
	if len(v.BodyMd) > 100000 {
		return fmt.Errorf("field 'BodyMd' must have at most 100000 elements")
	}
	return nil
}

// ValidateEditCommentRequest validates the EditCommentRequest struct
func (v *EditCommentRequest) Validate() error {
	if len(v.BodyMd) < 1 {
		return fmt.Errorf("field 'BodyMd' must have at least 1 elements")
	}
	if len(v.BodyMd) > 100000 {
		return fmt.Errorf("field 'BodyMd' must have at most 100000 elements")
	}
	return nil
}

// ValidateFriendGroup validates the FriendGroup struct
func (v *FriendGroup) Validate() error {
	if len(v.Name) < 1 {
		return fmt.Errorf("field 'Name' must have at least 1 elements")
	}
	if len(v.Name) > 128 {
		return fmt.Errorf("field 'Name' must have at most 128 elements")
	}
	return nil
}

// ValidateCreateFriendGroupRequest validates the CreateFriendGroupRequest struct
func (v *CreateFriendGroupRequest) Validate() error {
	if len(v.Name) < 1 {
		return fmt.Errorf("field 'Name' must have at least 1 elements")
	}
	if len(v.Name) > 128 {
		return fmt.Errorf("field 'Name' must have at most 128 elements")
	}
	return nil
}

// ValidateListNotificationsRequest validates the ListNotificationsRequest struct
func (v *ListNotificationsRequest) Validate() error {
	if v.Limit != nil {
		if (*v.Limit) > 200 {
			return fmt.Errorf("field 'Limit' must be <= 200")
		}
	}
	return nil
}

// ValidateGithubMapping validates the GithubMapping struct
func (v *GithubMapping) Validate() error {
	if len(v.Repo) < 3 {
		return fmt.Errorf("field 'Repo' must have at least 3 elements")
	}
	if len(v.Repo) > 256 {
		return fmt.Errorf("field 'Repo' must have at most 256 elements")
	}
	matched, _ := regexp.MatchString(`^[^/]+/[^/]+$`, v.Repo)
	if !matched {
		return fmt.Errorf("field 'Repo' must match pattern '^[^/]+/[^/]+$'")
	}
	return nil
}

// ValidateCreateMappingRequest validates the CreateMappingRequest struct
func (v *CreateMappingRequest) Validate() error {
	if len(v.Repo) < 3 {
		return fmt.Errorf("field 'Repo' must have at least 3 elements")
	}
	if len(v.Repo) > 256 {
		return fmt.Errorf("field 'Repo' must have at most 256 elements")
	}
	matched, _ := regexp.MatchString(`^[^/]+/[^/]+$`, v.Repo)
	if !matched {
		return fmt.Errorf("field 'Repo' must match pattern '^[^/]+/[^/]+$'")
	}
	if len(v.Events) < 1 {
		return fmt.Errorf("field 'Events' must have at least 1 elements")
	}
	if len(v.Events) > 20 {
		return fmt.Errorf("field 'Events' must have at most 20 elements")
	}
	return nil
}

// ValidateDomainEntry validates the DomainEntry struct
func (v *DomainEntry) Validate() error {
	if len(v.Domain) < 1 {
		return fmt.Errorf("field 'Domain' must have at least 1 elements")
	}
	if len(v.Domain) > 253 {
		return fmt.Errorf("field 'Domain' must have at most 253 elements")
	}
	return nil
}
